//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Qwe;
    using Qwe.ApplicationLayer.DTO;
    using Qwe.ApplicationLayer.DTO.Department;
    using Qwe.ApplicationLayer.Helpers;
    using Qwe.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для Department.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class DepartmentController : ControllerBase
    {
        private readonly IDepartmentService _departmentService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="DepartmentController"/>.
        /// </summary>
        /// <param name="departmentService">Сервис для работы с Department.</param>
        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех Department в форме AuditViewDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("AuditView")]
        public async Task<ActionResult<GetAllRequestResult<AuditViewDto>>> GetAllAuditView(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<AuditViewDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Department по идентификатору в форме AuditViewDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="AuditViewDto"/>, если найден.</returns>
        [HttpGet("AuditView/{id:guid}")]
        public async Task<ActionResult<AuditViewDto>> GetByIdAuditView(Guid id)
        {
            return await GetById<AuditViewDto>(id);
        }

        /// <summary>
        /// Получить общее количество Department.
        /// </summary>
        /// <returns>Количество Department.</returns>
        [HttpGet("AuditView/count")]
        public async Task<ActionResult<int>> GetCountAuditView()
        {
            return await GetCount<AuditViewDto>();
        }

        /// <summary>
        /// Получить список всех Department в форме DepartmentDDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("DepartmentD")]
        public async Task<ActionResult<GetAllRequestResult<DepartmentDDto>>> GetAllDepartmentD(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<DepartmentDDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Department по идентификатору в форме DepartmentDDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="DepartmentDDto"/>, если найден.</returns>
        [HttpGet("DepartmentD/{id:guid}")]
        public async Task<ActionResult<DepartmentDDto>> GetByIdDepartmentD(Guid id)
        {
            return await GetById<DepartmentDDto>(id);
        }

        /// <summary>
        /// Получить общее количество Department.
        /// </summary>
        /// <returns>Количество Department.</returns>
        [HttpGet("DepartmentD/count")]
        public async Task<ActionResult<int>> GetCountDepartmentD()
        {
            return await GetCount<DepartmentDDto>();
        }

        /// <summary>
        /// Получить список всех Department в форме DepartmentEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("DepartmentE")]
        public async Task<ActionResult<GetAllRequestResult<DepartmentEDto>>> GetAllDepartmentE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<DepartmentEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Department по идентификатору в форме DepartmentEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="DepartmentEDto"/>, если найден.</returns>
        [HttpGet("DepartmentE/{id:guid}")]
        public async Task<ActionResult<DepartmentEDto>> GetByIdDepartmentE(Guid id)
        {
            return await GetById<DepartmentEDto>(id);
        }

        /// <summary>
        /// Получить общее количество Department.
        /// </summary>
        /// <returns>Количество Department.</returns>
        [HttpGet("DepartmentE/count")]
        public async Task<ActionResult<int>> GetCountDepartmentE()
        {
            return await GetCount<DepartmentEDto>();
        }

        /// <summary>
        /// Получить список всех Department в форме DepartmentLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("DepartmentL")]
        public async Task<ActionResult<GetAllRequestResult<DepartmentLDto>>> GetAllDepartmentL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null, [FromQuery] DepartmentLFilterDto filter = null)
        {
            return await GetAll<DepartmentLDto>(perPage, page, sorting, filter);
        }

        /// <summary>
        /// Получить Department по идентификатору в форме DepartmentLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="DepartmentLDto"/>, если найден.</returns>
        [HttpGet("DepartmentL/{id:guid}")]
        public async Task<ActionResult<DepartmentLDto>> GetByIdDepartmentL(Guid id)
        {
            return await GetById<DepartmentLDto>(id);
        }

        /// <summary>
        /// Получить общее количество Department.
        /// </summary>
        /// <returns>Количество Department.</returns>
        [HttpGet("DepartmentL/count")]
        public async Task<ActionResult<int>> GetCountDepartmentL()
        {
            return await GetCount<DepartmentLDto>();
        }

        /// <summary>
        /// Создать новый Department в форме DepartmentEDto.
        /// </summary>
        /// <param name="dto">DTO с данными для создания.</param>
        /// <returns>Созданный <see cref="DepartmentEDto"/>.</returns>
        [HttpPost("DepartmentE")]
        public async Task<ActionResult<DepartmentEDto>> CreateDepartmentE([FromBody] DepartmentEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                Department created = await _departmentService.Create(dto);
                DepartmentEDto createdDto = new DepartmentEDto(created);

                return CreatedAtAction(nameof(GetByIdDepartmentE), new { id = createdDto.Id }, createdDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при создании Department", ex);

                return BadRequest();
            }
        }

        /// <summary>
        /// Обновить или создать Department в форме DepartmentEDto.
        /// </summary>
        /// <param name="dto">DTO с новыми данными.</param>
        /// <returns>Обновленный Department.</returns>
        [HttpPut("DepartmentE")]
        public async Task<ActionResult<DepartmentEDto>> UpdateDepartmentE([FromBody] DepartmentEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                DepartmentEDto existed = await _departmentService.GetOrDefaultById<DepartmentEDto>(dto.Id);
                Department createdOrUpdated = new ();

                if (existed == null)
                {
                    createdOrUpdated = await _departmentService.Create(dto);
                }
                else
                {
                    createdOrUpdated = await _departmentService.Update(dto);
                }

                DepartmentEDto updatedDto = new (createdOrUpdated);

                return Ok(updatedDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при обновлении Department", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить Department.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _departmentService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Department", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все Department для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _departmentService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Department", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех Department.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список Department.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : DepartmentDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _departmentService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _departmentService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Department", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить Department по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>Department в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : DepartmentDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _departmentService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Department по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество Department.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество Department.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : DepartmentDtoBase, new()
        {
            try
            {
                int result = await _departmentService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва Department", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
