//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.WebAPI.Controllers
{
    using System;
    using System.Text.Json;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Unity;
    using Qwe.ApplicationLayer.DTO;
    using Qwe.ApplicationLayer.DTO.Department;
    using Qwe.ApplicationLayer.DTO.Faculty;
    using Qwe.ApplicationLayer.DTO.Group;
    using Qwe.ApplicationLayer.DTO.Schedule;
    using Qwe.ApplicationLayer.DTO.Student;
    using Qwe.ApplicationLayer.DTO.StudyPlan;
    using Qwe.ApplicationLayer.DTO.Teacher;
    using Qwe.ApplicationLayer.ExportProviders;

    /// <summary>
    /// Контроллер экспорта списковых форм в Excel.
    /// </summary>
    [ApiController]
    [Route("export")]
    public class ExportController : ControllerBase
    {
        private readonly IUnityContainer _container;

        public ExportController(IUnityContainer container)
        {
            _container = container;
        }

        /// <summary>
        /// Экспорт DepartmentL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("DepartmentL")]
        public async Task<IActionResult> ExportDepartmentL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] DepartmentLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<DepartmentDtoBase> provider = _container.Resolve<IExcelExportProvider<DepartmentDtoBase>>("DepartmentLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<DepartmentLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "DepartmentL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Экспорт FacultyL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("FacultyL")]
        public async Task<IActionResult> ExportFacultyL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] FacultyLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<FacultyDtoBase> provider = _container.Resolve<IExcelExportProvider<FacultyDtoBase>>("FacultyLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<FacultyLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "FacultyL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Экспорт GroupL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("GroupL")]
        public async Task<IActionResult> ExportGroupL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] GroupLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<GroupDtoBase> provider = _container.Resolve<IExcelExportProvider<GroupDtoBase>>("GroupLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<GroupLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "GroupL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Экспорт ScheduleL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("ScheduleL")]
        public async Task<IActionResult> ExportScheduleL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] ScheduleLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<ScheduleDtoBase> provider = _container.Resolve<IExcelExportProvider<ScheduleDtoBase>>("ScheduleLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<ScheduleLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "ScheduleL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Экспорт StudentL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("StudentL")]
        public async Task<IActionResult> ExportStudentL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] StudentLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<StudentDtoBase> provider = _container.Resolve<IExcelExportProvider<StudentDtoBase>>("StudentLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<StudentLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "StudentL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Экспорт StudyPlanL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("StudyPlanL")]
        public async Task<IActionResult> ExportStudyPlanL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] StudyPlanLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<StudyPlanDtoBase> provider = _container.Resolve<IExcelExportProvider<StudyPlanDtoBase>>("StudyPlanLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<StudyPlanLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "StudyPlanL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Экспорт TeacherL в Excel.
        /// </summary>
        /// <param name="sorting">Параметры сортировки.</param>
        /// <param name="columns">JSON-массив имён видимых колонок для экспорта.</param>
        /// <param name="filter">Фильтр списка.</param>
        /// <returns>XLSX-файл с экспортированными данными.</returns>
        [HttpGet("TeacherL")]
        public async Task<IActionResult> ExportTeacherL(
            [FromQuery] string[] sorting,
            [FromQuery] string columns,
            [FromQuery] TeacherLFilterDto filter)
        {
            string[] fieldNames = JsonSerializer.Deserialize<string[]>(columns ?? "[]") ?? Array.Empty<string>();
            if (fieldNames.Length == 0)
            {
                return BadRequest("Не указаны колонки для экспорта.");
            }

            IExcelExportProvider<TeacherDtoBase> provider = _container.Resolve<IExcelExportProvider<TeacherDtoBase>>("TeacherLExportProvider");

            try
            {
                byte[] xlsx = await provider.ExportAsync<TeacherLDto>(fieldNames, sorting, filter);
                return File(
                    xlsx,
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "TeacherL.xlsx");
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
    }
}
