//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Qwe;
    using Qwe.ApplicationLayer.DTO;
    using Qwe.ApplicationLayer.DTO.Faculty;
    using Qwe.ApplicationLayer.Helpers;
    using Qwe.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для Faculty.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class FacultyController : ControllerBase
    {
        private readonly IFacultyService _facultyService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="FacultyController"/>.
        /// </summary>
        /// <param name="facultyService">Сервис для работы с Faculty.</param>
        public FacultyController(IFacultyService facultyService)
        {
            _facultyService = facultyService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех Faculty в форме FacultyEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("FacultyE")]
        public async Task<ActionResult<GetAllRequestResult<FacultyEDto>>> GetAllFacultyE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<FacultyEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Faculty по идентификатору в форме FacultyEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="FacultyEDto"/>, если найден.</returns>
        [HttpGet("FacultyE/{id:guid}")]
        public async Task<ActionResult<FacultyEDto>> GetByIdFacultyE(Guid id)
        {
            return await GetById<FacultyEDto>(id);
        }

        /// <summary>
        /// Получить общее количество Faculty.
        /// </summary>
        /// <returns>Количество Faculty.</returns>
        [HttpGet("FacultyE/count")]
        public async Task<ActionResult<int>> GetCountFacultyE()
        {
            return await GetCount<FacultyEDto>();
        }

        /// <summary>
        /// Получить список всех Faculty в форме FacultyLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("FacultyL")]
        public async Task<ActionResult<GetAllRequestResult<FacultyLDto>>> GetAllFacultyL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null, [FromQuery] FacultyLFilterDto filter = null)
        {
            return await GetAll<FacultyLDto>(perPage, page, sorting, filter);
        }

        /// <summary>
        /// Получить Faculty по идентификатору в форме FacultyLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="FacultyLDto"/>, если найден.</returns>
        [HttpGet("FacultyL/{id:guid}")]
        public async Task<ActionResult<FacultyLDto>> GetByIdFacultyL(Guid id)
        {
            return await GetById<FacultyLDto>(id);
        }

        /// <summary>
        /// Получить общее количество Faculty.
        /// </summary>
        /// <returns>Количество Faculty.</returns>
        [HttpGet("FacultyL/count")]
        public async Task<ActionResult<int>> GetCountFacultyL()
        {
            return await GetCount<FacultyLDto>();
        }

        /// <summary>
        /// Создать новый Faculty в форме FacultyEDto.
        /// </summary>
        /// <param name="dto">DTO с данными для создания.</param>
        /// <returns>Созданный <see cref="FacultyEDto"/>.</returns>
        [HttpPost("FacultyE")]
        public async Task<ActionResult<FacultyEDto>> CreateFacultyE([FromBody] FacultyEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                Faculty created = await _facultyService.Create(dto);
                FacultyEDto createdDto = new FacultyEDto(created);

                return CreatedAtAction(nameof(GetByIdFacultyE), new { id = createdDto.Id }, createdDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при создании Faculty", ex);

                return BadRequest();
            }
        }

        /// <summary>
        /// Обновить или создать Faculty в форме FacultyEDto.
        /// </summary>
        /// <param name="dto">DTO с новыми данными.</param>
        /// <returns>Обновленный Faculty.</returns>
        [HttpPut("FacultyE")]
        public async Task<ActionResult<FacultyEDto>> UpdateFacultyE([FromBody] FacultyEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                FacultyEDto existed = await _facultyService.GetOrDefaultById<FacultyEDto>(dto.Id);
                Faculty createdOrUpdated = new ();

                if (existed == null)
                {
                    createdOrUpdated = await _facultyService.Create(dto);
                }
                else
                {
                    createdOrUpdated = await _facultyService.Update(dto);
                }

                FacultyEDto updatedDto = new (createdOrUpdated);

                return Ok(updatedDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при обновлении Faculty", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить Faculty.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _facultyService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Faculty", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все Faculty для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _facultyService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Faculty", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех Faculty.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список Faculty.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : FacultyDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _facultyService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _facultyService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Faculty", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить Faculty по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>Faculty в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : FacultyDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _facultyService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Faculty по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество Faculty.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество Faculty.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : FacultyDtoBase, new()
        {
            try
            {
                int result = await _facultyService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва Faculty", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
