//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Qwe;
    using Qwe.ApplicationLayer.DTO;
    using Qwe.ApplicationLayer.DTO.Lesson;
    using Qwe.ApplicationLayer.Helpers;
    using Qwe.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для Lesson.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class LessonController : ControllerBase
    {
        private readonly ILessonService _lessonService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="LessonController"/>.
        /// </summary>
        /// <param name="lessonService">Сервис для работы с Lesson.</param>
        public LessonController(ILessonService lessonService)
        {
            _lessonService = lessonService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех Lesson в форме LessonDDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("LessonD")]
        public async Task<ActionResult<GetAllRequestResult<LessonDDto>>> GetAllLessonD(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<LessonDDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Lesson по идентификатору в форме LessonDDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="LessonDDto"/>, если найден.</returns>
        [HttpGet("LessonD/{id:guid}")]
        public async Task<ActionResult<LessonDDto>> GetByIdLessonD(Guid id)
        {
            return await GetById<LessonDDto>(id);
        }

        /// <summary>
        /// Получить общее количество Lesson.
        /// </summary>
        /// <returns>Количество Lesson.</returns>
        [HttpGet("LessonD/count")]
        public async Task<ActionResult<int>> GetCountLessonD()
        {
            return await GetCount<LessonDDto>();
        }

        /// <summary>
        /// Получить список всех Lesson в форме LessonLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("LessonL")]
        public async Task<ActionResult<GetAllRequestResult<LessonLDto>>> GetAllLessonL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<LessonLDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Lesson по идентификатору в форме LessonLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="LessonLDto"/>, если найден.</returns>
        [HttpGet("LessonL/{id:guid}")]
        public async Task<ActionResult<LessonLDto>> GetByIdLessonL(Guid id)
        {
            return await GetById<LessonLDto>(id);
        }

        /// <summary>
        /// Получить общее количество Lesson.
        /// </summary>
        /// <returns>Количество Lesson.</returns>
        [HttpGet("LessonL/count")]
        public async Task<ActionResult<int>> GetCountLessonL()
        {
            return await GetCount<LessonLDto>();
        }

        /// <summary>
        /// Удалить Lesson.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _lessonService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Lesson", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все Lesson для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _lessonService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Lesson", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех Lesson.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список Lesson.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : LessonDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _lessonService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _lessonService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Lesson", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить Lesson по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>Lesson в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : LessonDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _lessonService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Lesson по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество Lesson.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество Lesson.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : LessonDtoBase, new()
        {
            try
            {
                int result = await _lessonService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва Lesson", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
