//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Qwe;
    using Qwe.ApplicationLayer.DTO;
    using Qwe.ApplicationLayer.DTO.Schedule;
    using Qwe.ApplicationLayer.Helpers;
    using Qwe.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для Schedule.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class ScheduleController : ControllerBase
    {
        private readonly IScheduleService _scheduleService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ScheduleController"/>.
        /// </summary>
        /// <param name="scheduleService">Сервис для работы с Schedule.</param>
        public ScheduleController(IScheduleService scheduleService)
        {
            _scheduleService = scheduleService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех Schedule в форме ScheduleEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("ScheduleE")]
        public async Task<ActionResult<GetAllRequestResult<ScheduleEDto>>> GetAllScheduleE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<ScheduleEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Schedule по идентификатору в форме ScheduleEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="ScheduleEDto"/>, если найден.</returns>
        [HttpGet("ScheduleE/{id:guid}")]
        public async Task<ActionResult<ScheduleEDto>> GetByIdScheduleE(Guid id)
        {
            return await GetById<ScheduleEDto>(id);
        }

        /// <summary>
        /// Получить общее количество Schedule.
        /// </summary>
        /// <returns>Количество Schedule.</returns>
        [HttpGet("ScheduleE/count")]
        public async Task<ActionResult<int>> GetCountScheduleE()
        {
            return await GetCount<ScheduleEDto>();
        }

        /// <summary>
        /// Получить список всех Schedule в форме ScheduleLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("ScheduleL")]
        public async Task<ActionResult<GetAllRequestResult<ScheduleLDto>>> GetAllScheduleL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null, [FromQuery] ScheduleLFilterDto filter = null)
        {
            return await GetAll<ScheduleLDto>(perPage, page, sorting, filter);
        }

        /// <summary>
        /// Получить Schedule по идентификатору в форме ScheduleLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="ScheduleLDto"/>, если найден.</returns>
        [HttpGet("ScheduleL/{id:guid}")]
        public async Task<ActionResult<ScheduleLDto>> GetByIdScheduleL(Guid id)
        {
            return await GetById<ScheduleLDto>(id);
        }

        /// <summary>
        /// Получить общее количество Schedule.
        /// </summary>
        /// <returns>Количество Schedule.</returns>
        [HttpGet("ScheduleL/count")]
        public async Task<ActionResult<int>> GetCountScheduleL()
        {
            return await GetCount<ScheduleLDto>();
        }

        /// <summary>
        /// Создать новый Schedule в форме ScheduleEDto.
        /// </summary>
        /// <param name="dto">DTO с данными для создания.</param>
        /// <returns>Созданный <see cref="ScheduleEDto"/>.</returns>
        [HttpPost("ScheduleE")]
        public async Task<ActionResult<ScheduleEDto>> CreateScheduleE([FromBody] ScheduleEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                Schedule created = await _scheduleService.Create(dto);
                ScheduleEDto createdDto = new ScheduleEDto(created);

                return CreatedAtAction(nameof(GetByIdScheduleE), new { id = createdDto.Id }, createdDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при создании Schedule", ex);

                return BadRequest();
            }
        }

        /// <summary>
        /// Обновить или создать Schedule в форме ScheduleEDto.
        /// </summary>
        /// <param name="dto">DTO с новыми данными.</param>
        /// <returns>Обновленный Schedule.</returns>
        [HttpPut("ScheduleE")]
        public async Task<ActionResult<ScheduleEDto>> UpdateScheduleE([FromBody] ScheduleEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                ScheduleEDto existed = await _scheduleService.GetOrDefaultById<ScheduleEDto>(dto.Id);
                Schedule createdOrUpdated = new ();

                if (existed == null)
                {
                    createdOrUpdated = await _scheduleService.Create(dto);
                }
                else
                {
                    createdOrUpdated = await _scheduleService.Update(dto);
                }

                ScheduleEDto updatedDto = new (createdOrUpdated);

                return Ok(updatedDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при обновлении Schedule", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить Schedule.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _scheduleService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Schedule", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все Schedule для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _scheduleService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Schedule", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех Schedule.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список Schedule.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : ScheduleDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _scheduleService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _scheduleService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Schedule", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить Schedule по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>Schedule в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : ScheduleDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _scheduleService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Schedule по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество Schedule.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество Schedule.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : ScheduleDtoBase, new()
        {
            try
            {
                int result = await _scheduleService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва Schedule", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
