//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Qwe;
    using Qwe.ApplicationLayer.DTO;
    using Qwe.ApplicationLayer.DTO.ScheduleGroup;
    using Qwe.ApplicationLayer.Helpers;
    using Qwe.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для ScheduleGroup.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class ScheduleGroupController : ControllerBase
    {
        private readonly IScheduleGroupService _scheduleGroupService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ScheduleGroupController"/>.
        /// </summary>
        /// <param name="scheduleGroupService">Сервис для работы с ScheduleGroup.</param>
        public ScheduleGroupController(IScheduleGroupService scheduleGroupService)
        {
            _scheduleGroupService = scheduleGroupService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех ScheduleGroup в форме ScheduleGroupDDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("ScheduleGroupD")]
        public async Task<ActionResult<GetAllRequestResult<ScheduleGroupDDto>>> GetAllScheduleGroupD(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<ScheduleGroupDDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить ScheduleGroup по идентификатору в форме ScheduleGroupDDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="ScheduleGroupDDto"/>, если найден.</returns>
        [HttpGet("ScheduleGroupD/{id:guid}")]
        public async Task<ActionResult<ScheduleGroupDDto>> GetByIdScheduleGroupD(Guid id)
        {
            return await GetById<ScheduleGroupDDto>(id);
        }

        /// <summary>
        /// Получить общее количество ScheduleGroup.
        /// </summary>
        /// <returns>Количество ScheduleGroup.</returns>
        [HttpGet("ScheduleGroupD/count")]
        public async Task<ActionResult<int>> GetCountScheduleGroupD()
        {
            return await GetCount<ScheduleGroupDDto>();
        }

        /// <summary>
        /// Удалить ScheduleGroup.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _scheduleGroupService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении ScheduleGroup", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все ScheduleGroup для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _scheduleGroupService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении ScheduleGroup", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех ScheduleGroup.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список ScheduleGroup.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : ScheduleGroupDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _scheduleGroupService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _scheduleGroupService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении ScheduleGroup", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить ScheduleGroup по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>ScheduleGroup в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : ScheduleGroupDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _scheduleGroupService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении ScheduleGroup по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество ScheduleGroup.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество ScheduleGroup.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : ScheduleGroupDtoBase, new()
        {
            try
            {
                int result = await _scheduleGroupService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва ScheduleGroup", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
