//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Qwe;
    using Qwe.ApplicationLayer.DTO;
    using Qwe.ApplicationLayer.DTO.StudentBrigades;
    using Qwe.ApplicationLayer.Helpers;
    using Qwe.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для StudentBrigades.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class StudentBrigadesController : ControllerBase
    {
        private readonly IStudentBrigadesService _studentBrigadesService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="StudentBrigadesController"/>.
        /// </summary>
        /// <param name="studentBrigadesService">Сервис для работы с StudentBrigades.</param>
        public StudentBrigadesController(IStudentBrigadesService studentBrigadesService)
        {
            _studentBrigadesService = studentBrigadesService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех StudentBrigades в форме StudentBrigadesDDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("StudentBrigadesD")]
        public async Task<ActionResult<GetAllRequestResult<StudentBrigadesDDto>>> GetAllStudentBrigadesD(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<StudentBrigadesDDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить StudentBrigades по идентификатору в форме StudentBrigadesDDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="StudentBrigadesDDto"/>, если найден.</returns>
        [HttpGet("StudentBrigadesD/{id:guid}")]
        public async Task<ActionResult<StudentBrigadesDDto>> GetByIdStudentBrigadesD(Guid id)
        {
            return await GetById<StudentBrigadesDDto>(id);
        }

        /// <summary>
        /// Получить общее количество StudentBrigades.
        /// </summary>
        /// <returns>Количество StudentBrigades.</returns>
        [HttpGet("StudentBrigadesD/count")]
        public async Task<ActionResult<int>> GetCountStudentBrigadesD()
        {
            return await GetCount<StudentBrigadesDDto>();
        }

        /// <summary>
        /// Создать новый StudentBrigades в форме StudentBrigadesDDto.
        /// </summary>
        /// <param name="dto">DTO с данными для создания.</param>
        /// <returns>Созданный <see cref="StudentBrigadesDDto"/>.</returns>
        [HttpPost("StudentBrigadesD")]
        public async Task<ActionResult<StudentBrigadesDDto>> CreateStudentBrigadesD([FromBody] StudentBrigadesDDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                StudentBrigades created = await _studentBrigadesService.Create(dto);
                StudentBrigadesDDto createdDto = new StudentBrigadesDDto(created);

                return CreatedAtAction(nameof(GetByIdStudentBrigadesD), new { id = createdDto.Id }, createdDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при создании StudentBrigades", ex);

                return BadRequest();
            }
        }

        /// <summary>
        /// Обновить или создать StudentBrigades в форме StudentBrigadesDDto.
        /// </summary>
        /// <param name="dto">DTO с новыми данными.</param>
        /// <returns>Обновленный StudentBrigades.</returns>
        [HttpPut("StudentBrigadesD")]
        public async Task<ActionResult<StudentBrigadesDDto>> UpdateStudentBrigadesD([FromBody] StudentBrigadesDDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                StudentBrigadesDDto existed = await _studentBrigadesService.GetOrDefaultById<StudentBrigadesDDto>(dto.Id);
                StudentBrigades createdOrUpdated = new ();

                if (existed == null)
                {
                    createdOrUpdated = await _studentBrigadesService.Create(dto);
                }
                else
                {
                    createdOrUpdated = await _studentBrigadesService.Update(dto);
                }

                StudentBrigadesDDto updatedDto = new (createdOrUpdated);

                return Ok(updatedDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при обновлении StudentBrigades", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить StudentBrigades.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _studentBrigadesService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении StudentBrigades", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все StudentBrigades для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _studentBrigadesService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении StudentBrigades", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех StudentBrigades.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список StudentBrigades.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : StudentBrigadesDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _studentBrigadesService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _studentBrigadesService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении StudentBrigades", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить StudentBrigades по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>StudentBrigades в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : StudentBrigadesDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _studentBrigadesService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении StudentBrigades по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество StudentBrigades.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество StudentBrigades.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : StudentBrigadesDtoBase, new()
        {
            try
            {
                int result = await _studentBrigadesService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва StudentBrigades", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
