//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Qwe;
    using Qwe.ApplicationLayer.DTO;
    using Qwe.ApplicationLayer.DTO.Student;
    using Qwe.ApplicationLayer.Helpers;
    using Qwe.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для Student.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class StudentController : ControllerBase
    {
        private readonly IStudentService _studentService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="StudentController"/>.
        /// </summary>
        /// <param name="studentService">Сервис для работы с Student.</param>
        public StudentController(IStudentService studentService)
        {
            _studentService = studentService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех Student в форме StudentEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("StudentE")]
        public async Task<ActionResult<GetAllRequestResult<StudentEDto>>> GetAllStudentE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<StudentEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить Student по идентификатору в форме StudentEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="StudentEDto"/>, если найден.</returns>
        [HttpGet("StudentE/{id:guid}")]
        public async Task<ActionResult<StudentEDto>> GetByIdStudentE(Guid id)
        {
            return await GetById<StudentEDto>(id);
        }

        /// <summary>
        /// Получить общее количество Student.
        /// </summary>
        /// <returns>Количество Student.</returns>
        [HttpGet("StudentE/count")]
        public async Task<ActionResult<int>> GetCountStudentE()
        {
            return await GetCount<StudentEDto>();
        }

        /// <summary>
        /// Получить список всех Student в форме StudentLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("StudentL")]
        public async Task<ActionResult<GetAllRequestResult<StudentLDto>>> GetAllStudentL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null, [FromQuery] StudentLFilterDto filter = null)
        {
            return await GetAll<StudentLDto>(perPage, page, sorting, filter);
        }

        /// <summary>
        /// Получить Student по идентификатору в форме StudentLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="StudentLDto"/>, если найден.</returns>
        [HttpGet("StudentL/{id:guid}")]
        public async Task<ActionResult<StudentLDto>> GetByIdStudentL(Guid id)
        {
            return await GetById<StudentLDto>(id);
        }

        /// <summary>
        /// Получить общее количество Student.
        /// </summary>
        /// <returns>Количество Student.</returns>
        [HttpGet("StudentL/count")]
        public async Task<ActionResult<int>> GetCountStudentL()
        {
            return await GetCount<StudentLDto>();
        }

        /// <summary>
        /// Создать новый Student в форме StudentEDto.
        /// </summary>
        /// <param name="dto">DTO с данными для создания.</param>
        /// <returns>Созданный <see cref="StudentEDto"/>.</returns>
        [HttpPost("StudentE")]
        public async Task<ActionResult<StudentEDto>> CreateStudentE([FromBody] StudentEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                Student created = await _studentService.Create(dto);
                StudentEDto createdDto = new StudentEDto(created);

                return CreatedAtAction(nameof(GetByIdStudentE), new { id = createdDto.Id }, createdDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при создании Student", ex);

                return BadRequest();
            }
        }

        /// <summary>
        /// Обновить или создать Student в форме StudentEDto.
        /// </summary>
        /// <param name="dto">DTO с новыми данными.</param>
        /// <returns>Обновленный Student.</returns>
        [HttpPut("StudentE")]
        public async Task<ActionResult<StudentEDto>> UpdateStudentE([FromBody] StudentEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                StudentEDto existed = await _studentService.GetOrDefaultById<StudentEDto>(dto.Id);
                Student createdOrUpdated = new ();

                if (existed == null)
                {
                    createdOrUpdated = await _studentService.Create(dto);
                }
                else
                {
                    createdOrUpdated = await _studentService.Update(dto);
                }

                StudentEDto updatedDto = new (createdOrUpdated);

                return Ok(updatedDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при обновлении Student", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить Student.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _studentService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Student", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все Student для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _studentService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении Student", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех Student.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список Student.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : StudentDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _studentService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _studentService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Student", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить Student по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>Student в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : StudentDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _studentService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении Student по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество Student.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество Student.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : StudentDtoBase, new()
        {
            try
            {
                int result = await _studentService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва Student", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
