//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Qwe;
    using Qwe.ApplicationLayer.DTO;
    using Qwe.ApplicationLayer.DTO.StudyPlan;
    using Qwe.ApplicationLayer.Helpers;
    using Qwe.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для StudyPlan.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class StudyPlanController : ControllerBase
    {
        private readonly IStudyPlanService _studyPlanService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="StudyPlanController"/>.
        /// </summary>
        /// <param name="studyPlanService">Сервис для работы с StudyPlan.</param>
        public StudyPlanController(IStudyPlanService studyPlanService)
        {
            _studyPlanService = studyPlanService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех StudyPlan в форме StudyPlanEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("StudyPlanE")]
        public async Task<ActionResult<GetAllRequestResult<StudyPlanEDto>>> GetAllStudyPlanE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<StudyPlanEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить StudyPlan по идентификатору в форме StudyPlanEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="StudyPlanEDto"/>, если найден.</returns>
        [HttpGet("StudyPlanE/{id:guid}")]
        public async Task<ActionResult<StudyPlanEDto>> GetByIdStudyPlanE(Guid id)
        {
            return await GetById<StudyPlanEDto>(id);
        }

        /// <summary>
        /// Получить общее количество StudyPlan.
        /// </summary>
        /// <returns>Количество StudyPlan.</returns>
        [HttpGet("StudyPlanE/count")]
        public async Task<ActionResult<int>> GetCountStudyPlanE()
        {
            return await GetCount<StudyPlanEDto>();
        }

        /// <summary>
        /// Получить список всех StudyPlan в форме StudyPlanLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("StudyPlanL")]
        public async Task<ActionResult<GetAllRequestResult<StudyPlanLDto>>> GetAllStudyPlanL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null, [FromQuery] StudyPlanLFilterDto filter = null)
        {
            return await GetAll<StudyPlanLDto>(perPage, page, sorting, filter);
        }

        /// <summary>
        /// Получить StudyPlan по идентификатору в форме StudyPlanLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="StudyPlanLDto"/>, если найден.</returns>
        [HttpGet("StudyPlanL/{id:guid}")]
        public async Task<ActionResult<StudyPlanLDto>> GetByIdStudyPlanL(Guid id)
        {
            return await GetById<StudyPlanLDto>(id);
        }

        /// <summary>
        /// Получить общее количество StudyPlan.
        /// </summary>
        /// <returns>Количество StudyPlan.</returns>
        [HttpGet("StudyPlanL/count")]
        public async Task<ActionResult<int>> GetCountStudyPlanL()
        {
            return await GetCount<StudyPlanLDto>();
        }

        /// <summary>
        /// Создать новый StudyPlan в форме StudyPlanEDto.
        /// </summary>
        /// <param name="dto">DTO с данными для создания.</param>
        /// <returns>Созданный <see cref="StudyPlanEDto"/>.</returns>
        [HttpPost("StudyPlanE")]
        public async Task<ActionResult<StudyPlanEDto>> CreateStudyPlanE([FromBody] StudyPlanEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                StudyPlan created = await _studyPlanService.Create(dto);
                StudyPlanEDto createdDto = new StudyPlanEDto(created);

                return CreatedAtAction(nameof(GetByIdStudyPlanE), new { id = createdDto.Id }, createdDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при создании StudyPlan", ex);

                return BadRequest();
            }
        }

        /// <summary>
        /// Обновить или создать StudyPlan в форме StudyPlanEDto.
        /// </summary>
        /// <param name="dto">DTO с новыми данными.</param>
        /// <returns>Обновленный StudyPlan.</returns>
        [HttpPut("StudyPlanE")]
        public async Task<ActionResult<StudyPlanEDto>> UpdateStudyPlanE([FromBody] StudyPlanEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                StudyPlanEDto existed = await _studyPlanService.GetOrDefaultById<StudyPlanEDto>(dto.Id);
                StudyPlan createdOrUpdated = new ();

                if (existed == null)
                {
                    createdOrUpdated = await _studyPlanService.Create(dto);
                }
                else
                {
                    createdOrUpdated = await _studyPlanService.Update(dto);
                }

                StudyPlanEDto updatedDto = new (createdOrUpdated);

                return Ok(updatedDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при обновлении StudyPlan", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить StudyPlan.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _studyPlanService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении StudyPlan", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все StudyPlan для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _studyPlanService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении StudyPlan", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех StudyPlan.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список StudyPlan.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : StudyPlanDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _studyPlanService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _studyPlanService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении StudyPlan", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить StudyPlan по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>StudyPlan в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : StudyPlanDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _studyPlanService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении StudyPlan по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество StudyPlan.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество StudyPlan.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : StudyPlanDtoBase, new()
        {
            try
            {
                int result = await _studyPlanService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва StudyPlan", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
