//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { StudyPlanService } from '@/services/StudyPlan.service';

const useDeleteStudyPlan = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteStudyPlan,
    mutateAsync: deleteStudyPlanAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => StudyPlanService.DeleteStudyPlan(id),
    onSuccess: (_, id) => {
      const className = 'studyPlan';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteStudyPlan, deleteStudyPlanAsync, isPending };
};

export default useDeleteStudyPlan;
