//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { StudyPlanService } from '@/services/StudyPlan.service';
import { IBaseStudyPlan } from '@/types/StudyPlan.types';

const useUpdateStudyPlan = <T extends IBaseStudyPlan>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type UpdateRecordArgs = {
    studyPlan: T;
    viewName: string;
  };

  const {
    mutate: updateStudyPlan,
    mutateAsync: updateStudyPlanAsync,
    isPending,
  } = useMutation({
    mutationFn: (updateRecordArgs: UpdateRecordArgs) =>
      StudyPlanService.UpdateStudyPlan<T>(updateRecordArgs.studyPlan, updateRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'studyPlan';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { updateStudyPlan, updateStudyPlanAsync, isPending };
};

export default useUpdateStudyPlan;
