//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseAudience {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseAudience custom)

  // *** End programmer edit section *** (IBaseAudience custom)
}

export interface IAudienceE extends IBaseAudience {
  name: string;
  // *** Start programmer edit section *** (IAudienceE custom)

  // *** End programmer edit section *** (IAudienceE custom)
}

export interface IAudienceL extends IBaseAudience {
  name: string;
  // *** Start programmer edit section *** (IAudienceL custom)

  // *** End programmer edit section *** (IAudienceL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
