//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { tDirection } from '../enums/tDirection.types';
import { IGroupD as IGroupGroupD } from './Group.types';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseDepartment {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseDepartment custom)

  // *** End programmer edit section *** (IBaseDepartment custom)
}

export interface IAuditView extends IBaseDepartment {
  name: string;
  foundationDate: Date | null;
  facultyId: NonEmptyString;
  // *** Start programmer edit section *** (IAuditView custom)

  // *** End programmer edit section *** (IAuditView custom)
}

export interface IDepartmentD extends IBaseDepartment {
  name: string;
  specialization: tDirection;
  hasAdditionalEducation: boolean;
  foundationDate: Date | null;
  document: WebFile | null;
  // *** Start programmer edit section *** (IDepartmentD custom)

  // *** End programmer edit section *** (IDepartmentD custom)
}

export interface IDepartmentE extends IBaseDepartment {
  name: string;
  foundationDate: Date | null;
  hasAdditionalEducation: boolean;
  specialization: tDirection;
  document: WebFile | null;
  facultyId: NonEmptyString;
  group: IGroupGroupD[];
  // *** Start programmer edit section *** (IDepartmentE custom)

  // *** End programmer edit section *** (IDepartmentE custom)
}

export interface IDepartmentL extends IBaseDepartment {
  name: string;
  foundationDate: Date | null;
  hasAdditionalEducation: boolean;
  specialization: tDirection;
  // *** Start programmer edit section *** (IDepartmentL custom)

  // *** End programmer edit section *** (IDepartmentL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
