//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { tFacultyType } from '../enums/tFacultyType.types';
import { IDepartmentD as IDepartmentDepartmentD } from './Department.types';
import { IStudentBrigadesD as IStudentBrigadesStudentBrigadesD } from './StudentBrigades.types';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseFaculty {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseFaculty custom)

  // *** End programmer edit section *** (IBaseFaculty custom)
}

export interface IFacultyE extends IBaseFaculty {
  name: string;
  foundationDate: Date | null;
  hasMilitaryDepartment: boolean;
  type: tFacultyType;
  department: IDepartmentDepartmentD[];
  studentBrigades: IStudentBrigadesStudentBrigadesD[];
  // *** Start programmer edit section *** (IFacultyE custom)

  // *** End programmer edit section *** (IFacultyE custom)
}

export interface IFacultyL extends IBaseFaculty {
  name: string;
  foundationDate: Date | null;
  hasMilitaryDepartment: boolean;
  type: tFacultyType;
  // *** Start programmer edit section *** (IFacultyL custom)

  // *** End programmer edit section *** (IFacultyL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
