//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { tEducationForm } from '../enums/tEducationForm.types';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseGroup {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseGroup custom)

  // *** End programmer edit section *** (IBaseGroup custom)
}

export interface IGroupD extends IBaseGroup {
  name: string;
  fullName: string;
  form: tEducationForm;
  isMaster: boolean;
  enrollmentYear: Date | null;
  leaderId: NonEmptyString;
  leaderFullName: string;
  assistantId: NonEmptyString | null;
  assistantFullName: string;
  // *** Start programmer edit section *** (IGroupD custom)

  // *** End programmer edit section *** (IGroupD custom)
}

export interface IGroupE extends IBaseGroup {
  name: string;
  enrollmentYear: Date | null;
  form: tEducationForm;
  isMaster: boolean;
  fullName: string;
  departmentId: NonEmptyString;
  leaderId: NonEmptyString;
  leaderFullName: string;
  assistantId: NonEmptyString | null;
  assistantFullName: string;
  // *** Start programmer edit section *** (IGroupE custom)

  // *** End programmer edit section *** (IGroupE custom)
}

export interface IGroupL extends IBaseGroup {
  name: string;
  fullName: string;
  enrollmentYear: Date | null;
  form: tEducationForm;
  isMaster: boolean;
  // *** Start programmer edit section *** (IGroupL custom)

  // *** End programmer edit section *** (IGroupL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
