//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseLesson {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseLesson custom)

  // *** End programmer edit section *** (IBaseLesson custom)
}

export interface ILessonD extends IBaseLesson {
  subject: string;
  startTime: Date | null;
  endTime: Date | null;
  comment: string;
  teacherId: NonEmptyString;
  audienceId: NonEmptyString | null;
  // *** Start programmer edit section *** (ILessonD custom)

  // *** End programmer edit section *** (ILessonD custom)
}

export interface ILessonL extends IBaseLesson {
  scheduleDateFrom: Date | null;
  subject: string;
  startTime: Date | null;
  endTime: Date | null;
  teacherFullName: string;
  audienceName: string;
  comment: string;
  // *** Start programmer edit section *** (ILessonL custom)

  // *** End programmer edit section *** (ILessonL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
