//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseScheduleGroup {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseScheduleGroup custom)

  // *** End programmer edit section *** (IBaseScheduleGroup custom)
}

export interface IScheduleGroupD extends IBaseScheduleGroup {
  scheduleId: NonEmptyString;
  groupId: NonEmptyString;
  groupFullName: string;
  summary: string;
  // *** Start programmer edit section *** (IScheduleGroupD custom)

  // *** End programmer edit section *** (IScheduleGroupD custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
