//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { ILessonD as ILessonLessonD } from './Lesson.types';
import { IScheduleGroupD as IScheduleGroupScheduleGroupD } from './ScheduleGroup.types';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseSchedule {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseSchedule custom)

  // *** End programmer edit section *** (IBaseSchedule custom)
}

export interface IScheduleE extends IBaseSchedule {
  year: number;
  week: number;
  day: number;
  dateFrom: Date | null;
  lessons: ILessonLessonD[];
  groups: IScheduleGroupScheduleGroupD[];
  // *** Start programmer edit section *** (IScheduleE custom)

  // *** End programmer edit section *** (IScheduleE custom)
}

export interface IScheduleL extends IBaseSchedule {
  year: number;
  week: number;
  day: number;
  // *** Start programmer edit section *** (IScheduleL custom)

  // *** End programmer edit section *** (IScheduleL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
