//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseStudentBrigades {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseStudentBrigades custom)

  // *** End programmer edit section *** (IBaseStudentBrigades custom)
}

export interface IStudentBrigadesD extends IBaseStudentBrigades {
  participants: number;
  // *** Start programmer edit section *** (IStudentBrigadesD custom)

  // *** End programmer edit section *** (IStudentBrigadesD custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
