//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseStudyPlan {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseStudyPlan custom)

  // *** End programmer edit section *** (IBaseStudyPlan custom)
}

export interface IStudyPlanE extends IBaseStudyPlan {
  creationDate: Date | null;
  hasPractice: boolean;
  specialization: string;
  totalHours: number;
  // *** Start programmer edit section *** (IStudyPlanE custom)

  // *** End programmer edit section *** (IStudyPlanE custom)
}

export interface IStudyPlanL extends IBaseStudyPlan {
  creationDate: Date | null;
  hasPractice: boolean;
  specialization: string;
  totalHours: number;
  // *** Start programmer edit section *** (IStudyPlanL custom)

  // *** End programmer edit section *** (IStudyPlanL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
