//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { tStudentStatus } from '../enums/tStudentStatus.types';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseStudent {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseStudent custom)

  // *** End programmer edit section *** (IBaseStudent custom)
}

export interface IStudentE extends IBaseStudent {
  enrollmentDate: Date | null;
  fullName: string;
  isBudget: boolean;
  status: tStudentStatus;
  studentId: string;
  teacherId: NonEmptyString;
  planId: NonEmptyString;
  groupId: NonEmptyString | null;
  groupName: string;
  // *** Start programmer edit section *** (IStudentE custom)

  // *** End programmer edit section *** (IStudentE custom)
}

export interface IStudentL extends IBaseStudent {
  enrollmentDate: Date | null;
  fullName: string;
  isBudget: boolean;
  status: tStudentStatus;
  studentId: string;
  planHasPractice: boolean;
  // *** Start programmer edit section *** (IStudentL custom)

  // *** End programmer edit section *** (IStudentL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
