//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { tAcademicDegree } from '../enums/tAcademicDegree.types';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseTeacher {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseTeacher custom)

  // *** End programmer edit section *** (IBaseTeacher custom)
}

export interface ITeacherE extends IBaseTeacher {
  dateOfBirth: Date | null;
  degree: tAcademicDegree;
  fullName: string;
  partTime: boolean;
  studyPlanId: NonEmptyString | null;
  // *** Start programmer edit section *** (ITeacherE custom)

  // *** End programmer edit section *** (ITeacherE custom)
}

export interface ITeacherL extends IBaseTeacher {
  dateOfBirth: Date | null;
  degree: tAcademicDegree;
  fullName: string;
  partTime: boolean;
  // *** Start programmer edit section *** (ITeacherL custom)

  // *** End programmer edit section *** (ITeacherL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
