//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { ScheduleService } from '@/services/Schedule.service';

const useDeleteSchedule = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteSchedule,
    mutateAsync: deleteScheduleAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => ScheduleService.DeleteSchedule(id),
    onSuccess: (_, id) => {
      const className = 'schedule';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteSchedule, deleteScheduleAsync, isPending };
};

export default useDeleteSchedule;
