//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { ScheduleService } from '@/services/Schedule.service';
import { IBaseSchedule } from '@/types/Schedule.types';

const useUpdateSchedule = <T extends IBaseSchedule>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type UpdateRecordArgs = {
    schedule: T;
    viewName: string;
  };

  const {
    mutate: updateSchedule,
    mutateAsync: updateScheduleAsync,
    isPending,
  } = useMutation({
    mutationFn: (updateRecordArgs: UpdateRecordArgs) =>
      ScheduleService.UpdateSchedule<T>(updateRecordArgs.schedule, updateRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'schedule';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { updateSchedule, updateScheduleAsync, isPending };
};

export default useUpdateSchedule;
