//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Faculty
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Faculty.FacultyE.
    /// </summary>
    [DataView(typeof(Faculty), "FacultyE")]
    public partial class FacultyEDto : FacultyDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="FacultyEDto"/>.
        /// </summary>
        public FacultyEDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="FacultyEDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public FacultyEDto(Faculty source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Название.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("Название")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Дата основания.
        /// </summary>
        [PropertyName("FoundationDate")]
        [CaptionProperty("Дата основания")]
        public DateTime FoundationDate { get; set; } = DateTime.Now;

        /// <summary>
        /// Наличие военной кафедры.
        /// </summary>
        [PropertyName("HasMilitaryDepartment")]
        [CaptionProperty("Наличие военной кафедры")]
        public bool HasMilitaryDepartment { get; set; } = false;

        /// <summary>
        /// Профиль факультета.
        /// </summary>
        [PropertyName("Type")]
        [CaptionProperty("Профиль факультета")]
        public tFacultyType Type { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Кафедра.
        /// </summary>
        public List<DTO.Department.DepartmentDDto> Department { get; set; } = new List<DTO.Department.DepartmentDDto>();

        /// <summary>
        /// СтудОтряды.
        /// </summary>
        public List<DTO.StudentBrigades.StudentBrigadesDDto> StudentBrigades { get; set; } = new List<DTO.StudentBrigades.StudentBrigadesDDto>();

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override FacultyEDto FillFromClass(Faculty source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Name = source.Name;
            FoundationDate = source.FoundationDate.ToUniversalTime();
            HasMilitaryDepartment = source.HasMilitaryDepartment;
            Type = source.Type;
            Department = source.Department.GetAllObjects().Cast<Department>().Select(d => new DTO.Department.DepartmentDDto(d)).ToList();
            StudentBrigades = source.StudentBrigades.GetAllObjects().Cast<StudentBrigades>().Select(d => new DTO.StudentBrigades.StudentBrigadesDDto(d)).ToList();

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Faculty destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Name = Name;
            destination.FoundationDate = FoundationDate.ToUniversalTime();
            destination.HasMilitaryDepartment = HasMilitaryDepartment;
            destination.Type = Type;

            DataObject[] detailsDepartment = destination.Department.GetAllObjects();
            foreach (DTO.Department.DepartmentDDto detailDto in Department)
            {
                DataObject? detail = detailsDepartment.FirstOrDefault(l => PKHelper.EQPK(l, detailDto.Id));
                if (detail == null)
                {
                    detail = new Department() { Faculty = destination };
                    destination.Department.AddObject(detail);
                }

                detailDto.UpdateFromDto((Department)detail);
            }

            foreach (Department detail in detailsDepartment)
            {
                if (!Department.Any(a => PKHelper.EQPK(detail, a.Id)))
                {
                    detail.SetStatus(ObjectStatus.Deleted);
                }
            }

            DataObject[] detailsStudentBrigades = destination.StudentBrigades.GetAllObjects();
            foreach (DTO.StudentBrigades.StudentBrigadesDDto detailDto in StudentBrigades)
            {
                DataObject? detail = detailsStudentBrigades.FirstOrDefault(l => PKHelper.EQPK(l, detailDto.Id));
                if (detail == null)
                {
                    detail = new StudentBrigades() { Faculty = destination };
                    destination.StudentBrigades.AddObject(detail);
                }

                detailDto.UpdateFromDto((StudentBrigades)detail);
            }

            foreach (StudentBrigades detail in detailsStudentBrigades)
            {
                if (!StudentBrigades.Any(a => PKHelper.EQPK(detail, a.Id)))
                {
                    detail.SetStatus(ObjectStatus.Deleted);
                }
            }

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
