//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Faculty
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Qwe;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации FacultyL.
    /// </summary>
    public partial class FacultyLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FacultyLFilterDto"/> class.
        /// </summary>
        public FacultyLFilterDto()
        {
            DtoType = typeof(FacultyLDto);
        }

        /// <summary>
        /// Название.
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// Название.
        /// </summary>
        public FilterOperation? NameOp { get; set; }
        /// <summary>
        /// Дата основания.
        /// </summary>
        public DateTime? FoundationDate { get; set; }

        /// <summary>
        /// Дата основания.
        /// </summary>
        public FilterOperation? FoundationDateOp { get; set; }
        /// <summary>
        /// Наличие военной кафедры.
        /// </summary>
        public bool? HasMilitaryDepartment { get; set; }

        /// <summary>
        /// Наличие военной кафедры.
        /// </summary>
        public FilterOperation? HasMilitaryDepartmentOp { get; set; }
        /// <summary>
        /// Профиль факультета.
        /// </summary>
        public tFacultyType? Type { get; set; }

        /// <summary>
        /// Профиль факультета.
        /// </summary>
        public FilterOperation? TypeOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (NameOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Faculty>(NameOp.Value, d => d.Name, Name));
            }

            if (FoundationDateOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Faculty>(FoundationDateOp.Value, d => d.FoundationDate, FoundationDate));
            }

            if (HasMilitaryDepartmentOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Faculty>(HasMilitaryDepartmentOp.Value, d => d.HasMilitaryDepartment, HasMilitaryDepartment));
            }

            if (TypeOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Faculty>(TypeOp.Value, d => d.Type, Type));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
