//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Faculty
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Faculty.FacultyL.
    /// </summary>
    [DataView(typeof(Faculty), "FacultyL")]
    public partial class FacultyLDto : FacultyDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="FacultyLDto"/>.
        /// </summary>
        public FacultyLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="FacultyLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public FacultyLDto(Faculty source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Название.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("Название")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Дата основания.
        /// </summary>
        [PropertyName("FoundationDate")]
        [CaptionProperty("Дата основания")]
        public DateTime FoundationDate { get; set; } = DateTime.Now;

        /// <summary>
        /// Наличие военной кафедры.
        /// </summary>
        [PropertyName("HasMilitaryDepartment")]
        [CaptionProperty("Наличие военной кафедры")]
        public bool HasMilitaryDepartment { get; set; } = false;

        /// <summary>
        /// Профиль факультета.
        /// </summary>
        [PropertyName("Type")]
        [CaptionProperty("Профиль факультета")]
        public tFacultyType Type { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override FacultyLDto FillFromClass(Faculty source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Name = source.Name;
            FoundationDate = source.FoundationDate.ToUniversalTime();
            HasMilitaryDepartment = source.HasMilitaryDepartment;
            Type = source.Type;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Faculty destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Name = Name;
            destination.FoundationDate = FoundationDate.ToUniversalTime();
            destination.HasMilitaryDepartment = HasMilitaryDepartment;
            destination.Type = Type;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
