FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src
COPY Qwe/ ./Qwe/

WORKDIR /src/Qwe

RUN dotnet restore "Qwe.sln"
RUN dotnet publish "Qwe.WebAPI/Qwe.WebAPI.csproj" -c Release -f net10.0 --no-restore -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:10.0

WORKDIR /app
COPY --from=build /app/out ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "Qwe.WebAPI.dll"]
