//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { StudentService } from '@/services/Student.service';

const useDeleteStudent = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteStudent,
    mutateAsync: deleteStudentAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => StudentService.DeleteStudent(id),
    onSuccess: (_, id) => {
      const className = 'student';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteStudent, deleteStudentAsync, isPending };
};

export default useDeleteStudent;
