//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { GroupService } from '@/services/Group.service';
import { IBaseGroup } from '@/types/Group.types';

const useUpdateGroup = <T extends IBaseGroup>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type UpdateRecordArgs = {
    group: T;
    viewName: string;
  };

  const {
    mutate: updateGroup,
    mutateAsync: updateGroupAsync,
    isPending,
  } = useMutation({
    mutationFn: (updateRecordArgs: UpdateRecordArgs) =>
      GroupService.UpdateGroup<T>(updateRecordArgs.group, updateRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'group';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { updateGroup, updateGroupAsync, isPending };
};

export default useUpdateGroup;
