//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.StudentBrigades
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления StudentBrigades.StudentBrigadesD.
    /// </summary>
    [DataView(typeof(StudentBrigades), "StudentBrigadesD")]
    public partial class StudentBrigadesDDto : StudentBrigadesDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="StudentBrigadesDDto"/>.
        /// </summary>
        public StudentBrigadesDDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="StudentBrigadesDDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public StudentBrigadesDDto(StudentBrigades source)
        {
            FillFromClass(source);
        }

        /// <summary>
        /// Участники.
        /// </summary>
        [PropertyName("Participants")]
        [CaptionProperty("Участники")]
        public int Participants { get; set; } = 0;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override StudentBrigadesDDto FillFromClass(StudentBrigades source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Participants = source.Participants;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(StudentBrigades destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Participants = Participants;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
