//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { TeacherService } from '@/services/Teacher.service';

const useDeleteAllTeacher = (onSuccess: (result: string[]) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAllTeacher,
    mutateAsync: deleteAllTeacherAsync,
    isPending,
  } = useMutation({
    mutationFn: (ids: string[]) => TeacherService.DeleteAllTeacher(ids),
    onSuccess: (_, ids) => {
      const className = 'teacher';
      ids.forEach((id) => {
        queryClient.removeQueries({ queryKey: [className, id] });
      });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(ids);
    },
    onError: (e) => onError(e),
  });

  return { deleteAllTeacher, deleteAllTeacherAsync, isPending };
};

export default useDeleteAllTeacher;
