//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { TeacherService } from '@/services/Teacher.service';

const useDeleteTeacher = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteTeacher,
    mutateAsync: deleteTeacherAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => TeacherService.DeleteTeacher(id),
    onSuccess: (_, id) => {
      const className = 'teacher';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteTeacher, deleteTeacherAsync, isPending };
};

export default useDeleteTeacher;
