//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useQuery } from '@tanstack/react-query';

import { TeacherService } from '@/services/Teacher.service';

const useGetCountTeacher = (viewName: string) => {
  const { data, isLoading, isError } = useQuery({
    queryKey: ['teacher', 'count', viewName],
    retry: false,
    queryFn: async (): Promise<number> => {
      const response = await TeacherService.GetCount(viewName);
      return response.data;
    },
  });

  return {
    count: data || 0,
    isLoading,
    isError,
  };
};

export default useGetCountTeacher;
