//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { TeacherService } from '@/services/Teacher.service';
import { IBaseTeacher } from '@/types/Teacher.types';

const useUpdateTeacher = <T extends IBaseTeacher>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type UpdateRecordArgs = {
    teacher: T;
    viewName: string;
  };

  const {
    mutate: updateTeacher,
    mutateAsync: updateTeacherAsync,
    isPending,
  } = useMutation({
    mutationFn: (updateRecordArgs: UpdateRecordArgs) =>
      TeacherService.UpdateTeacher<T>(updateRecordArgs.teacher, updateRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'teacher';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { updateTeacher, updateTeacherAsync, isPending };
};

export default useUpdateTeacher;
