//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.Services
{
    using ICSSoft.STORMNET.Business;
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Qwe;
    using Qwe.ApplicationLayer.DTO;
    using Qwe.ApplicationLayer.DTO.Department;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Определяет операции для сущностей <see cref="Department"/>.
    /// </summary>
    public interface IDepartmentService
    {
        /// <summary>
        /// Получает все объекты в виде списка DTO.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Коллекция DTO.</returns>
        Task<IEnumerable<TDto>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase? filter = null)
            where TDto : DepartmentDtoBase, new();

        /// <summary>
        /// Получает сущность по ее уникальному идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор объекта.</param>
        /// <returns>Указанное ДТО.</returns>
        Task<TDto> GetById<TDto>(Guid id)
            where TDto : DepartmentDtoBase, new();

        /// <summary>
        /// Получает сущность по ее уникальному идентификатору или null, если сущность не существует.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор объекта.</param>
        /// <returns>Указанное ДТО.</returns>
        Task<TDto?> GetOrDefaultById<TDto>(Guid id)
            where TDto : DepartmentDtoBase, new();

        /// <summary>
        /// Возвращает общее количество объектов.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество объектов.</returns>
        Task<int> Count<TDto>(FilterDtoBase? filter = null)
            where TDto : DepartmentDtoBase, new();

        /// <summary>
        /// Строит LoadingCustomizationStruct с учётом сортировки, фильтрации и бизнес-ограничений.
        /// </summary>
        Task<LoadingCustomizationStruct> BuildLcs<TDto>(int? perPage = null, int? page = null, string[]? sorting = null, FilterDtoBase? filter = null)
            where TDto : DepartmentDtoBase, new();

        /// <summary>
        /// Создаёт новый объект.
        /// </summary>
        /// <param name="dto">DTO с данными нового объекта.</param>
        /// <returns>Созданный объект.</returns>
        Task<Department> Create(DepartmentEDto dto);

        /// <summary>
        /// Обновляет существующий объект.
        /// </summary>
        /// <param name="dto">DTO с обновлёнными данными объекта.</param>
        /// <returns>Обновлённый объект.</returns>
        Task<Department> Update(DepartmentEDto dto);

        /// <summary>
        /// Удаляет объект.
        /// </summary>
        /// <param name="id">Уникальный идентификатор удаляемого объекта.</param>
        /// <returns><c>true</c>, если удаление прошло успешно.</returns>
        Task<bool> Delete(Guid id);

        /// <summary>
        /// Удаляет объекты.
        /// </summary>
        /// <param name="ids">Уникальные идентификаторы удаляемых объектов.</param>
        /// <returns><c>true</c>, если удаление прошло успешно.</returns>
        Task<bool> DeleteAll(List<Guid> ids);

        // *** Start programmer edit section *** (Custom methods)

        // *** End programmer edit section *** (Custom methods)
    }
}
