//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Group
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Group.GroupD.
    /// </summary>
    [DataView(typeof(Group), "GroupD")]
    public partial class GroupDDto : GroupDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="GroupDDto"/>.
        /// </summary>
        public GroupDDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="GroupDDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public GroupDDto(Group source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Название.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("Название")]
        public string Name { get; set; } = string.Empty;

                /// <summary>
        /// Полное название группы.
        /// </summary>
        [PropertyName("FullName")]
        [CaptionProperty("Полное название группы")]
        public string FullName { get; set; } = string.Empty;

        /// <summary>
        /// Форма обучения.
        /// </summary>
        [PropertyName("Form")]
        [CaptionProperty("Форма обучения")]
        public tEducationForm Form { get; set; }

        /// <summary>
        /// Магистратура.
        /// </summary>
        [PropertyName("IsMaster")]
        [CaptionProperty("Магистратура")]
        public bool IsMaster { get; set; } = false;

        /// <summary>
        /// Год поступления.
        /// </summary>
        [PropertyName("EnrollmentYear")]
        [CaptionProperty("Год поступления")]
        public DateTime EnrollmentYear { get; set; } = DateTime.Now;

        /// <summary>
        /// Староста.
        /// </summary>
        [PropertyName("Leader")]
        [CaptionProperty("Староста")]
        public Guid LeaderId { get; set; }

        /// <summary>
        /// ФИО старосты.
        /// </summary>
        [PropertyName("Leader.FullName")]
        [CaptionProperty("ФИО старосты")]
        public string? LeaderFullName { get; set; }

        /// <summary>
        /// Помощник старосты.
        /// </summary>
        [PropertyName("Assistant")]
        [CaptionProperty("Помощник старосты")]
        public Guid? AssistantId { get; set; }

        /// <summary>
        /// ФИО помощника старосты.
        /// </summary>
        [PropertyName("Assistant.FullName")]
        [CaptionProperty("ФИО помощника старосты")]
        public string? AssistantFullName { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override GroupDDto FillFromClass(Group source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Name = source.Name;
            FullName = source.FullName;
            Form = source.Form;
            IsMaster = source.IsMaster;
            EnrollmentYear = source.EnrollmentYear.ToUniversalTime();
            LeaderId = PKHelper.GetGuidByObject(source.Leader).GetValueOrDefault();
            LeaderFullName = source.Leader?.FullName ?? string.Empty;
            AssistantId = PKHelper.GetGuidByObject(source.Assistant);
            AssistantFullName = source.Assistant?.FullName ?? string.Empty;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Group destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Name = Name;
            destination.FullName = FullName;
            destination.Form = Form;
            destination.IsMaster = IsMaster;
            destination.EnrollmentYear = EnrollmentYear.ToUniversalTime();

            if (LeaderId != Guid.Empty)
            {
                Student leader = new Student();
                leader.SetExistObjectPrimaryKey(LeaderId);
                destination.Leader = leader;
            }
            else
            {
                destination.Leader = null;
            }

            if (AssistantId.HasValue)
            {
                Student assistant = new Student();
                assistant.SetExistObjectPrimaryKey(AssistantId);
                destination.Assistant = assistant;
            }
            else
            {
                destination.Assistant = null;
            }

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
