//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Audience
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Audience.AudienceL.
    /// </summary>
    [DataView(typeof(Audience), "AudienceL")]
    public partial class AudienceLDto : AudienceDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AudienceLDto"/>.
        /// </summary>
        public AudienceLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AudienceLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public AudienceLDto(Audience source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Наименование.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("Наименование")]
        public string Name { get; set; } = string.Empty;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override AudienceLDto FillFromClass(Audience source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Name = source.Name;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Audience destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Name = Name;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
