//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseDepartment } from '@/types/Department.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const DepartmentService = {
  async GetAllDepartment(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/department/${viewName}${queryStr}`);
  },

  async GetDepartment(id: string, viewName: string) {
    return await axiosInstance.get(`/department/${viewName}/${id}`);
  },

  async CreateDepartment<T extends IBaseDepartment>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/department/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateDepartment<T extends IBaseDepartment>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/department/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteDepartment(id: string) {
    return await axiosInstance.delete(`/department/${id}`);
  },

  async DeleteAllDepartment(ids: string[]) {
    return await axiosInstance.post(`/department/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/department/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
