//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseFaculty } from '@/types/Faculty.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const FacultyService = {
  async GetAllFaculty(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/faculty/${viewName}${queryStr}`);
  },

  async GetFaculty(id: string, viewName: string) {
    return await axiosInstance.get(`/faculty/${viewName}/${id}`);
  },

  async CreateFaculty<T extends IBaseFaculty>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/faculty/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateFaculty<T extends IBaseFaculty>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/faculty/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteFaculty(id: string) {
    return await axiosInstance.delete(`/faculty/${id}`);
  },

  async DeleteAllFaculty(ids: string[]) {
    return await axiosInstance.post(`/faculty/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/faculty/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
