//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseLesson } from '@/types/Lesson.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const LessonService = {
  async GetAllLesson(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/lesson/${viewName}${queryStr}`);
  },

  async GetLesson(id: string, viewName: string) {
    return await axiosInstance.get(`/lesson/${viewName}/${id}`);
  },

  async CreateLesson<T extends IBaseLesson>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/lesson/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateLesson<T extends IBaseLesson>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/lesson/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteLesson(id: string) {
    return await axiosInstance.delete(`/lesson/${id}`);
  },

  async DeleteAllLesson(ids: string[]) {
    return await axiosInstance.post(`/lesson/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/lesson/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
