//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseScheduleGroup } from '@/types/ScheduleGroup.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const ScheduleGroupService = {
  async GetAllScheduleGroup(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/schedulegroup/${viewName}${queryStr}`);
  },

  async GetScheduleGroup(id: string, viewName: string) {
    return await axiosInstance.get(`/schedulegroup/${viewName}/${id}`);
  },

  async CreateScheduleGroup<T extends IBaseScheduleGroup>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/schedulegroup/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateScheduleGroup<T extends IBaseScheduleGroup>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/schedulegroup/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteScheduleGroup(id: string) {
    return await axiosInstance.delete(`/schedulegroup/${id}`);
  },

  async DeleteAllScheduleGroup(ids: string[]) {
    return await axiosInstance.post(`/schedulegroup/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/schedulegroup/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
