//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseSchedule } from '@/types/Schedule.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const ScheduleService = {
  async GetAllSchedule(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/schedule/${viewName}${queryStr}`);
  },

  async GetSchedule(id: string, viewName: string) {
    return await axiosInstance.get(`/schedule/${viewName}/${id}`);
  },

  async CreateSchedule<T extends IBaseSchedule>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/schedule/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateSchedule<T extends IBaseSchedule>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/schedule/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteSchedule(id: string) {
    return await axiosInstance.delete(`/schedule/${id}`);
  },

  async DeleteAllSchedule(ids: string[]) {
    return await axiosInstance.post(`/schedule/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/schedule/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
