//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseStudentBrigades } from '@/types/StudentBrigades.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const StudentBrigadesService = {
  async GetAllStudentBrigades(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/studentbrigades/${viewName}${queryStr}`);
  },

  async GetStudentBrigades(id: string, viewName: string) {
    return await axiosInstance.get(`/studentbrigades/${viewName}/${id}`);
  },

  async CreateStudentBrigades<T extends IBaseStudentBrigades>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/studentbrigades/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateStudentBrigades<T extends IBaseStudentBrigades>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/studentbrigades/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteStudentBrigades(id: string) {
    return await axiosInstance.delete(`/studentbrigades/${id}`);
  },

  async DeleteAllStudentBrigades(ids: string[]) {
    return await axiosInstance.post(`/studentbrigades/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/studentbrigades/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
