//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseStudyPlan } from '@/types/StudyPlan.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const StudyPlanService = {
  async GetAllStudyPlan(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/studyplan/${viewName}${queryStr}`);
  },

  async GetStudyPlan(id: string, viewName: string) {
    return await axiosInstance.get(`/studyplan/${viewName}/${id}`);
  },

  async CreateStudyPlan<T extends IBaseStudyPlan>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/studyplan/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateStudyPlan<T extends IBaseStudyPlan>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/studyplan/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteStudyPlan(id: string) {
    return await axiosInstance.delete(`/studyplan/${id}`);
  },

  async DeleteAllStudyPlan(ids: string[]) {
    return await axiosInstance.post(`/studyplan/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/studyplan/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
