//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseTeacher } from '@/types/Teacher.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const TeacherService = {
  async GetAllTeacher(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/teacher/${viewName}${queryStr}`);
  },

  async GetTeacher(id: string, viewName: string) {
    return await axiosInstance.get(`/teacher/${viewName}/${id}`);
  },

  async CreateTeacher<T extends IBaseTeacher>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/teacher/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateTeacher<T extends IBaseTeacher>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/teacher/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteTeacher(id: string) {
    return await axiosInstance.delete(`/teacher/${id}`);
  },

  async DeleteAllTeacher(ids: string[]) {
    return await axiosInstance.post(`/teacher/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/teacher/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
