//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { LessonService } from '@/services/Lesson.service';

const useDeleteLesson = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteLesson,
    mutateAsync: deleteLessonAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => LessonService.DeleteLesson(id),
    onSuccess: (_, id) => {
      const className = 'lesson';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteLesson, deleteLessonAsync, isPending };
};

export default useDeleteLesson;
