//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { LessonService } from '@/services/Lesson.service';

const useDeleteAllLesson = (onSuccess: (result: string[]) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAllLesson,
    mutateAsync: deleteAllLessonAsync,
    isPending,
  } = useMutation({
    mutationFn: (ids: string[]) => LessonService.DeleteAllLesson(ids),
    onSuccess: (_, ids) => {
      const className = 'lesson';
      ids.forEach((id) => {
        queryClient.removeQueries({ queryKey: [className, id] });
      });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(ids);
    },
    onError: (e) => onError(e),
  });

  return { deleteAllLesson, deleteAllLessonAsync, isPending };
};

export default useDeleteAllLesson;
