//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { LessonService } from '@/services/Lesson.service';
import { IBaseLesson } from '@/types/Lesson.types';

const useUpdateLesson = <T extends IBaseLesson>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type UpdateRecordArgs = {
    lesson: T;
    viewName: string;
  };

  const {
    mutate: updateLesson,
    mutateAsync: updateLessonAsync,
    isPending,
  } = useMutation({
    mutationFn: (updateRecordArgs: UpdateRecordArgs) =>
      LessonService.UpdateLesson<T>(updateRecordArgs.lesson, updateRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'lesson';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { updateLesson, updateLessonAsync, isPending };
};

export default useUpdateLesson;
