//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
export enum tView {
  AudienceE = 'AudienceE',
  AudienceL = 'AudienceL',
  AuditView = 'AuditView',
  DepartmentD = 'DepartmentD',
  DepartmentE = 'DepartmentE',
  DepartmentL = 'DepartmentL',
  FacultyE = 'FacultyE',
  FacultyL = 'FacultyL',
  GroupD = 'GroupD',
  GroupE = 'GroupE',
  GroupL = 'GroupL',
  LessonD = 'LessonD',
  LessonL = 'LessonL',
  ScheduleE = 'ScheduleE',
  ScheduleGroupD = 'ScheduleGroupD',
  ScheduleL = 'ScheduleL',
  StudentBrigadesD = 'StudentBrigadesD',
  StudentE = 'StudentE',
  StudentL = 'StudentL',
  StudyPlanE = 'StudyPlanE',
  StudyPlanL = 'StudyPlanL',
  TeacherE = 'TeacherE',
  TeacherL = 'TeacherL',
  // *** Start programmer edit section *** (Additional views)

  // *** End programmer edit section *** (Additional views)
}
