//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { StudentBrigadesService } from '@/services/StudentBrigades.service';
import { IBaseStudentBrigades } from '@/types/StudentBrigades.types';

const useCreateStudentBrigades = <T extends IBaseStudentBrigades>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type CreateRecordArgs = {
    studentBrigades: T;
    viewName: string;
  };

  const {
    mutate: createStudentBrigades,
    mutateAsync: createStudentBrigadesAsync,
    isPending,
  } = useMutation({
    mutationFn: (createRecordArgs: CreateRecordArgs) =>
      StudentBrigadesService.CreateStudentBrigades<T>(createRecordArgs.studentBrigades, createRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'studentBrigades';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { createStudentBrigades, createStudentBrigadesAsync, isPending };
};

export default useCreateStudentBrigades;
