//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { StudentBrigadesService } from '@/services/StudentBrigades.service';

const useDeleteStudentBrigades = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteStudentBrigades,
    mutateAsync: deleteStudentBrigadesAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => StudentBrigadesService.DeleteStudentBrigades(id),
    onSuccess: (_, id) => {
      const className = 'studentBrigades';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteStudentBrigades, deleteStudentBrigadesAsync, isPending };
};

export default useDeleteStudentBrigades;
