//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useEffect } from 'react';
import { isAxiosError } from 'axios';
import { useQuery } from '@tanstack/react-query';

import { StudentBrigadesService } from '@/services/StudentBrigades.service';
import type { IBaseStudentBrigades } from '@/types/StudentBrigades.types';
import type { GetRequestOptions } from '@/types/helpers/GetRequestOptions';

const useGetStudentBrigades = <T extends IBaseStudentBrigades>({
  id,
  viewName,
  enabled = true,
  onNotFound,
}: GetRequestOptions) => {
  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['studentBrigades', id],
    retry: false,
    enabled: enabled,
    queryFn: async (): Promise<T> => {
      const response = await StudentBrigadesService.GetStudentBrigades(id, viewName);
      return response.data;
    },
  });

  useEffect(() => {
    if (isError && isAxiosError(error)) {
      if (typeof onNotFound === 'function' && error.response?.status === 404) {
        onNotFound();
      }
    }
  }, [error, isError, onNotFound]);

  return {
    data,
    isLoading,
    isError,
  };
};

export default useGetStudentBrigades;
