//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.ExportProviders
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    using NewPlatform.Flexberry;
    using NewPlatform.Flexberry.Reports.ExportToExcel;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;
    using Qwe.ApplicationLayer.Services;
    using Qwe.ApplicationLayer.DTO;
    using Qwe.ApplicationLayer.DTO.Schedule;

    /// <summary>
    /// Провайдер экспорта ScheduleL в Excel.
    /// </summary>
    public class ScheduleLExportProvider : IExcelExportProvider<ScheduleDtoBase>
    {
        private readonly IScheduleService _service;

        private readonly IDataService _dataService;

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ScheduleLExportProvider"/>.
        /// </summary>
        /// <param name="service">Сервис работы с Schedule.</param>
        /// <param name="dataService">Сервис доступа к данным.</param>
        public ScheduleLExportProvider(
            IScheduleService service,
            IDataService dataService)
        {
            _service = service;
            _dataService = dataService;
        }

        /// <inheritdoc/>
        public string EntityName => "Schedule";

        /// <inheritdoc/>
        public async Task<byte[]> ExportAsync<TDto>(string[] columns, string[] sorting, FilterDtoBase? filter)
            where TDto : ScheduleDtoBase, new()
        {
            LoadingCustomizationStruct lcs = await _service.BuildLcs<TDto>(null, null, sorting, filter);

            DataObject[] dataObjects = _dataService.LoadObjects(lcs);

            List<string> properties = MapColumnsToProperties(columns, typeof(TDto));
            List<IHeaderCaption> captions = ResolveCaptionsAsync(columns, properties, typeof(TDto));

            ExportParams exportParams = new ()
            {
                View = lcs.View,
                PropertiesOrder = properties,
                HeaderCaptions = captions,
            };

            DataExportLimitedService dataExportService = new (exportParams, _dataService);
            IDataExport dataExport = dataExportService.GetDataExport(dataObjects);
            ExcelExportService excelService = new (exportParams, null);
            return excelService.GetExportStream(dataExport).ToArray();
        }

        /// <summary>
        /// Получает заголовки колонок.
        /// </summary>
        /// <param name="columns">Массив имён колонок (camelCase).</param>
        /// <param name="properties">Соответствующие имена свойств DataObject.</param>
        /// <returns>Список заголовков для экспорта.</returns>
        private List<IHeaderCaption> ResolveCaptionsAsync(string[] columns, List<string> properties, Type dtoType)
        {
            List<IHeaderCaption> result = new();

            for (int i = 0; i < columns.Length; i++)
            {
                string pascalName = Capitalize(columns[i]);
                PropertyInfo? prop = dtoType.GetProperty(pascalName);
                CaptionPropertyAttribute? captionAttr = prop?.GetCustomAttributes(typeof(CaptionPropertyAttribute), false)
                    .Cast<CaptionPropertyAttribute>().FirstOrDefault();

                result.Add(new HeaderCaption
                {
                    PropertyName = properties[i],
                    Caption = captionAttr?.Caption ?? pascalName,
                });
            }

            return result;
        }

        /// <summary>
        /// Маппит имена колонок (camelCase) в имена свойств DataObject через PropertyNameAttribute.
        /// </summary>
        /// <param name="columns">Массив имён колонок (camelCase).</param>
        /// <param name="dtoType">Тип DTO для получения атрибутов.</param>
        /// <returns>Список имён свойств DataObject.</returns>
        private static List<string> MapColumnsToProperties(string[] columns, Type dtoType)
        {
            List<string> result = new ();
            foreach (string col in columns)
            {
                string pascalName = Capitalize(col);
                PropertyInfo? prop = dtoType.GetProperty(pascalName);
                PropertyNameAttribute? propNameAttr = prop?.GetCustomAttributes(typeof(PropertyNameAttribute), false)
                    .Cast<PropertyNameAttribute>().FirstOrDefault();
                result.Add(propNameAttr?.PropName ?? pascalName);
            }

            return result;
        }

        /// <summary>
        /// Делает первую букву строки заглавной.
        /// </summary>
        private static string Capitalize(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return value;
            }

            return char.ToUpper(value[0]) + value[1..];
        }
    }
}
