//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qwe
{


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// EmptyBS.
    /// </summary>
    // *** Start programmer edit section *** (EmptyBS CustomAttributes)

    // *** End programmer edit section *** (EmptyBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class EmptyBS : ICSSoft.STORMNET.Business.BusinessServer
    {

        // *** Start programmer edit section *** (EmptyBS CustomMembers)

        // *** End programmer edit section *** (EmptyBS CustomMembers)
    }
}
