//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qwe
{


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// FacultyBS.
    /// </summary>
    // *** Start programmer edit section *** (FacultyBS CustomAttributes)

    // *** End programmer edit section *** (FacultyBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class FacultyBS : ICSSoft.STORMNET.Business.BusinessServer
    {

        // *** Start programmer edit section *** (FacultyBS CustomMembers)

        // *** End programmer edit section *** (FacultyBS CustomMembers)

        // *** Start programmer edit section *** (OnUpdateFaculty CustomAttributes)

        // *** End programmer edit section *** (OnUpdateFaculty CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateFaculty(Qwe.Faculty UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateFaculty)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateFaculty)
        }
    }
}
