//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.ScheduleGroup
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления ScheduleGroup.ScheduleGroupD.
    /// </summary>
    [DataView(typeof(ScheduleGroup), "ScheduleGroupD")]
    public partial class ScheduleGroupDDto : ScheduleGroupDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ScheduleGroupDDto"/>.
        /// </summary>
        public ScheduleGroupDDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ScheduleGroupDDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public ScheduleGroupDDto(ScheduleGroup source)
        {
            FillFromClass(source);
        }

        /// <summary>
        /// Расписание.
        /// </summary>
        [PropertyName("Schedule")]
        [CaptionProperty("Расписание")]
        public Guid ScheduleId { get; set; }

        /// <summary>
        /// Группа.
        /// </summary>
        [PropertyName("Group")]
        [CaptionProperty("Группа")]
        public Guid GroupId { get; set; }

        /// <summary>
        /// Полное назание группы.
        /// </summary>
        [PropertyName("Group.FullName")]
        [CaptionProperty("Полное назание группы")]
        public string? GroupFullName { get; set; }

                /// <summary>
        /// Описание.
        /// </summary>
        [PropertyName("Summary")]
        [CaptionProperty("Описание")]
        public string Summary { get; set; } = string.Empty;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override ScheduleGroupDDto FillFromClass(ScheduleGroup source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            ScheduleId = PKHelper.GetGuidByObject(source.Schedule).GetValueOrDefault();
            GroupId = PKHelper.GetGuidByObject(source.Group).GetValueOrDefault();
            GroupFullName = source.Group?.FullName ?? string.Empty;
            Summary = source.Summary;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(ScheduleGroup destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Summary = Summary;

            if (ScheduleId != Guid.Empty)
            {
                Schedule schedule = new Schedule();
                schedule.SetExistObjectPrimaryKey(ScheduleId);
                destination.Schedule = schedule;
            }
            else
            {
                destination.Schedule = null;
            }

            if (GroupId != Guid.Empty)
            {
                Group group = new Group();
                group.SetExistObjectPrimaryKey(GroupId);
                destination.Group = group;
            }
            else
            {
                destination.Group = null;
            }

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
