//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Schedule
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Schedule.ScheduleL.
    /// </summary>
    [DataView(typeof(Schedule), "ScheduleL")]
    public partial class ScheduleLDto : ScheduleDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ScheduleLDto"/>.
        /// </summary>
        public ScheduleLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ScheduleLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public ScheduleLDto(Schedule source)
        {
            FillFromClass(source);
        }

        /// <summary>
        /// Год.
        /// </summary>
        [PropertyName("Year")]
        [CaptionProperty("Год")]
        public int Year { get; set; }

        /// <summary>
        /// Неделя.
        /// </summary>
        [PropertyName("Week")]
        [CaptionProperty("Неделя")]
        public int Week { get; set; }

        /// <summary>
        /// День.
        /// </summary>
        [PropertyName("Day")]
        [CaptionProperty("День")]
        public int Day { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override ScheduleLDto FillFromClass(Schedule source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Year = source.Year;
            Week = source.Week;
            Day = source.Day;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Schedule destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Year = Year;
            destination.Week = Week;
            destination.Day = Day;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
