//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Schedule
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Qwe;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации ScheduleL.
    /// </summary>
    public partial class ScheduleLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleLFilterDto"/> class.
        /// </summary>
        public ScheduleLFilterDto()
        {
            DtoType = typeof(ScheduleLDto);
        }

        /// <summary>
        /// Год.
        /// </summary>
        public int? Year { get; set; }

        /// <summary>
        /// Год.
        /// </summary>
        public FilterOperation? YearOp { get; set; }
        /// <summary>
        /// Неделя.
        /// </summary>
        public int? Week { get; set; }

        /// <summary>
        /// Неделя.
        /// </summary>
        public FilterOperation? WeekOp { get; set; }
        /// <summary>
        /// День.
        /// </summary>
        public int? Day { get; set; }

        /// <summary>
        /// День.
        /// </summary>
        public FilterOperation? DayOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (YearOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Schedule>(YearOp.Value, d => d.Year, Year));
            }

            if (WeekOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Schedule>(WeekOp.Value, d => d.Week, Week));
            }

            if (DayOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Schedule>(DayOp.Value, d => d.Day, Day));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
