//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Schedule
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Schedule.ScheduleE.
    /// </summary>
    [DataView(typeof(Schedule), "ScheduleE")]
    public partial class ScheduleEDto : ScheduleDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ScheduleEDto"/>.
        /// </summary>
        public ScheduleEDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ScheduleEDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public ScheduleEDto(Schedule source)
        {
            FillFromClass(source);
        }

        /// <summary>
        /// Год.
        /// </summary>
        [PropertyName("Year")]
        [CaptionProperty("Год")]
        public int Year { get; set; }

        /// <summary>
        /// Неделя.
        /// </summary>
        [PropertyName("Week")]
        [CaptionProperty("Неделя")]
        public int Week { get; set; }

        /// <summary>
        /// День.
        /// </summary>
        [PropertyName("Day")]
        [CaptionProperty("День")]
        public int Day { get; set; }

        /// <summary>
        /// Дата.
        /// </summary>
        [PropertyName("DateFrom")]
        [CaptionProperty("Дата")]
        public DateTime DateFrom { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Предметы.
        /// </summary>
        public List<DTO.Lesson.LessonDDto> Lessons { get; set; } = new List<DTO.Lesson.LessonDDto>();

        /// <summary>
        /// Группы.
        /// </summary>
        public List<DTO.ScheduleGroup.ScheduleGroupDDto> Groups { get; set; } = new List<DTO.ScheduleGroup.ScheduleGroupDDto>();

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override ScheduleEDto FillFromClass(Schedule source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Year = source.Year;
            Week = source.Week;
            Day = source.Day;
            DateFrom = source.DateFrom.ToUniversalTime();
            Lessons = source.Lessons.GetAllObjects().Cast<Lesson>().Select(d => new DTO.Lesson.LessonDDto(d)).ToList();
            Groups = source.Groups.GetAllObjects().Cast<ScheduleGroup>().Select(d => new DTO.ScheduleGroup.ScheduleGroupDDto(d)).ToList();

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Schedule destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Year = Year;
            destination.Week = Week;
            destination.Day = Day;
            destination.DateFrom = DateFrom.ToUniversalTime();

            DataObject[] detailsLessons = destination.Lessons.GetAllObjects();
            foreach (DTO.Lesson.LessonDDto detailDto in Lessons)
            {
                DataObject? detail = detailsLessons.FirstOrDefault(l => PKHelper.EQPK(l, detailDto.Id));
                if (detail == null)
                {
                    detail = new Lesson() { Schedule = destination };
                    destination.Lessons.AddObject(detail);
                }

                detailDto.UpdateFromDto((Lesson)detail);
            }

            foreach (Lesson detail in detailsLessons)
            {
                if (!Lessons.Any(a => PKHelper.EQPK(detail, a.Id)))
                {
                    detail.SetStatus(ObjectStatus.Deleted);
                }
            }

            DataObject[] detailsGroups = destination.Groups.GetAllObjects();
            foreach (DTO.ScheduleGroup.ScheduleGroupDDto detailDto in Groups)
            {
                DataObject? detail = detailsGroups.FirstOrDefault(l => PKHelper.EQPK(l, detailDto.Id));
                if (detail == null)
                {
                    detail = new ScheduleGroup() { Schedule = destination };
                    destination.Groups.AddObject(detail);
                }

                detailDto.UpdateFromDto((ScheduleGroup)detail);
            }

            foreach (ScheduleGroup detail in detailsGroups)
            {
                if (!Groups.Any(a => PKHelper.EQPK(detail, a.Id)))
                {
                    detail.SetStatus(ObjectStatus.Deleted);
                }
            }

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
