//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Lesson
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Lesson.LessonD.
    /// </summary>
    [DataView(typeof(Lesson), "LessonD")]
    public partial class LessonDDto : LessonDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="LessonDDto"/>.
        /// </summary>
        public LessonDDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="LessonDDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public LessonDDto(Lesson source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Предмет.
        /// </summary>
        [PropertyName("Subject")]
        [CaptionProperty("Предмет")]
        public string Subject { get; set; } = string.Empty;

        /// <summary>
        /// Время начала.
        /// </summary>
        [PropertyName("StartTime")]
        [CaptionProperty("Время начала")]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// Время окончания.
        /// </summary>
        [PropertyName("EndTime")]
        [CaptionProperty("Время окончания")]
        public DateTime EndTime { get; set; }

                /// <summary>
        /// Комментарий.
        /// </summary>
        [PropertyName("Comment")]
        [CaptionProperty("Комментарий")]
        public string Comment { get; set; } = string.Empty;

        /// <summary>
        /// Преподаватель.
        /// </summary>
        [PropertyName("Teacher")]
        [CaptionProperty("Преподаватель")]
        public Guid TeacherId { get; set; }

        /// <summary>
        /// Аудитория.
        /// </summary>
        [PropertyName("Audience")]
        [CaptionProperty("Аудитория")]
        public Guid? AudienceId { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override LessonDDto FillFromClass(Lesson source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Subject = source.Subject;
            StartTime = source.StartTime.ToUniversalTime();
            EndTime = source.EndTime.ToUniversalTime();
            Comment = source.Comment;
            TeacherId = PKHelper.GetGuidByObject(source.Teacher).GetValueOrDefault();
            AudienceId = PKHelper.GetGuidByObject(source.Audience);

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Lesson destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Subject = Subject;
            destination.StartTime = StartTime.ToUniversalTime();
            destination.EndTime = EndTime.ToUniversalTime();
            destination.Comment = Comment;

            if (TeacherId != Guid.Empty)
            {
                Teacher teacher = new Teacher();
                teacher.SetExistObjectPrimaryKey(TeacherId);
                destination.Teacher = teacher;
            }
            else
            {
                destination.Teacher = null;
            }

            if (AudienceId.HasValue)
            {
                Audience audience = new Audience();
                audience.SetExistObjectPrimaryKey(AudienceId);
                destination.Audience = audience;
            }
            else
            {
                destination.Audience = null;
            }

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
