//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Lesson
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Lesson.LessonL.
    /// </summary>
    [DataView(typeof(Lesson), "LessonL")]
    public partial class LessonLDto : LessonDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="LessonLDto"/>.
        /// </summary>
        public LessonLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="LessonLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public LessonLDto(Lesson source)
        {
            FillFromClass(source);
        }

        /// <summary>
        /// Дата.
        /// </summary>
        [PropertyName("Schedule.DateFrom")]
        [CaptionProperty("Дата")]
        public DateTime? ScheduleDateFrom { get; set; }

                /// <summary>
        /// Предмет.
        /// </summary>
        [PropertyName("Subject")]
        [CaptionProperty("Предмет")]
        public string Subject { get; set; } = string.Empty;

        /// <summary>
        /// Время начала.
        /// </summary>
        [PropertyName("StartTime")]
        [CaptionProperty("Время начала")]
        public DateTime StartTime { get; set; }

        /// <summary>
        /// Время окончания.
        /// </summary>
        [PropertyName("EndTime")]
        [CaptionProperty("Время окончания")]
        public DateTime EndTime { get; set; }

        /// <summary>
        /// Преподаватель.
        /// </summary>
        [PropertyName("Teacher.FullName")]
        [CaptionProperty("Преподаватель")]
        public string? TeacherFullName { get; set; }

        /// <summary>
        /// Аудитория.
        /// </summary>
        [PropertyName("Audience.Name")]
        [CaptionProperty("Аудитория")]
        public string? AudienceName { get; set; }

                /// <summary>
        /// Комментарий.
        /// </summary>
        [PropertyName("Comment")]
        [CaptionProperty("Комментарий")]
        public string Comment { get; set; } = string.Empty;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override LessonLDto FillFromClass(Lesson source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            ScheduleDateFrom = source.Schedule?.DateFrom.ToUniversalTime();
            Subject = source.Subject;
            StartTime = source.StartTime.ToUniversalTime();
            EndTime = source.EndTime.ToUniversalTime();
            TeacherFullName = source.Teacher?.FullName ?? string.Empty;
            AudienceName = source.Audience?.Name ?? string.Empty;
            Comment = source.Comment;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Lesson destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Subject = Subject;
            destination.StartTime = StartTime.ToUniversalTime();
            destination.EndTime = EndTime.ToUniversalTime();
            destination.Comment = Comment;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
