//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AudienceService } from '@/services/Audience.service';

const useDeleteAudience = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAudience,
    mutateAsync: deleteAudienceAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => AudienceService.DeleteAudience(id),
    onSuccess: (_, id) => {
      const className = 'audience';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteAudience, deleteAudienceAsync, isPending };
};

export default useDeleteAudience;
