//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useEffect } from 'react';
import { isAxiosError } from 'axios';
import { useQuery } from '@tanstack/react-query';

import { AudienceService } from '@/services/Audience.service';
import type { IBaseAudience } from '@/types/Audience.types';
import type { GetRequestOptions } from '@/types/helpers/GetRequestOptions';

const useGetAudience = <T extends IBaseAudience>({ id, viewName, enabled = true, onNotFound }: GetRequestOptions) => {
  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['audience', id],
    retry: false,
    enabled: enabled,
    queryFn: async (): Promise<T> => {
      const response = await AudienceService.GetAudience(id, viewName);
      return response.data;
    },
  });

  useEffect(() => {
    if (isError && isAxiosError(error)) {
      if (typeof onNotFound === 'function' && error.response?.status === 404) {
        onNotFound();
      }
    }
  }, [error, isError, onNotFound]);

  return {
    data,
    isLoading,
    isError,
  };
};

export default useGetAudience;
