//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qwe
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Аудитория.
    /// </summary>
    // *** Start programmer edit section *** (Audience CustomAttributes)

    // *** End programmer edit section *** (Audience CustomAttributes)
    [AutoAltered()]
    [Caption("Аудитория")]
    [View("AudienceE", new string[] {
            "Name as \'Наименование\'"})]
    [View("AudienceL", new string[] {
            "Name as \'Наименование\'"})]
    public class Audience : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        // *** Start programmer edit section *** (Audience CustomMembers)

        // *** End programmer edit section *** (Audience CustomMembers)


        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Audience.Name CustomAttributes)

        // *** End programmer edit section *** (Audience.Name CustomAttributes)
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Audience.Name Get start)

                // *** End programmer edit section *** (Audience.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Audience.Name Get end)

                // *** End programmer edit section *** (Audience.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Audience.Name Set start)

                // *** End programmer edit section *** (Audience.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Audience.Name Set end)

                // *** End programmer edit section *** (Audience.Name Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AudienceE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AudienceE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AudienceE", typeof(Qwe.Audience));
                }
            }

            /// <summary>
            /// "AudienceL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AudienceL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AudienceL", typeof(Qwe.Audience));
                }
            }
        }

    }
}
