//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qwe
{
    using System;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Факультет.
    /// </summary>
    // *** Start programmer edit section *** (Faculty CustomAttributes)

    // *** End programmer edit section *** (Faculty CustomAttributes)
    [BusinessServer("Qwe.FacultyBS, Qwe.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("Факультет")]
    [View("FacultyE", new string[] {
            "Name as \'Название\'",
            "FoundationDate as \'Дата основания\'",
            "HasMilitaryDepartment as \'Наличие военной кафедры\'",
            "Type as \'Профиль факультета\'"})]
    [AssociatedDetailViewAttribute("FacultyE", "Department", "DepartmentD", true, "", "Кафедра", true, new string[] {
            ""})]
    [AssociatedDetailViewAttribute("FacultyE", "StudentBrigades", "StudentBrigadesD", true, "", "СтудОтряды", true, new string[] {
            ""})]
    [View("FacultyL", new string[] {
            "Name as \'Название\'",
            "FoundationDate as \'Дата основания\'",
            "HasMilitaryDepartment as \'Наличие военной кафедры\'",
            "Type as \'Профиль факультета\'"})]
    public class Faculty : ICSSoft.STORMNET.DataObject
    {

        private System.DateTime fFoundationDate = DateTime.Now;

        private bool fHasMilitaryDepartment = false;

        private string fName;

        private tFacultyType fType;

        private Qwe.DetailArrayOfDepartment fDepartment;

        private Qwe.DetailArrayOfStudentBrigades fStudentBrigades;

        // *** Start programmer edit section *** (Faculty CustomMembers)

        // *** End programmer edit section *** (Faculty CustomMembers)


        /// <summary>
        /// Дата основания.
        /// </summary>
        // *** Start programmer edit section *** (Faculty.FoundationDate CustomAttributes)

        // *** End programmer edit section *** (Faculty.FoundationDate CustomAttributes)
        [NotNull()]
        public virtual System.DateTime FoundationDate
        {
            get
            {
                // *** Start programmer edit section *** (Faculty.FoundationDate Get start)

                // *** End programmer edit section *** (Faculty.FoundationDate Get start)
                System.DateTime result = this.fFoundationDate;
                // *** Start programmer edit section *** (Faculty.FoundationDate Get end)

                // *** End programmer edit section *** (Faculty.FoundationDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Faculty.FoundationDate Set start)

                // *** End programmer edit section *** (Faculty.FoundationDate Set start)
                this.fFoundationDate = value;
                // *** Start programmer edit section *** (Faculty.FoundationDate Set end)

                // *** End programmer edit section *** (Faculty.FoundationDate Set end)
            }
        }

        /// <summary>
        /// Военная кафедра.
        /// </summary>
        // *** Start programmer edit section *** (Faculty.HasMilitaryDepartment CustomAttributes)

        // *** End programmer edit section *** (Faculty.HasMilitaryDepartment CustomAttributes)
        [NotNull()]
        public virtual bool HasMilitaryDepartment
        {
            get
            {
                // *** Start programmer edit section *** (Faculty.HasMilitaryDepartment Get start)

                // *** End programmer edit section *** (Faculty.HasMilitaryDepartment Get start)
                bool result = this.fHasMilitaryDepartment;
                // *** Start programmer edit section *** (Faculty.HasMilitaryDepartment Get end)

                // *** End programmer edit section *** (Faculty.HasMilitaryDepartment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Faculty.HasMilitaryDepartment Set start)

                // *** End programmer edit section *** (Faculty.HasMilitaryDepartment Set start)
                this.fHasMilitaryDepartment = value;
                // *** Start programmer edit section *** (Faculty.HasMilitaryDepartment Set end)

                // *** End programmer edit section *** (Faculty.HasMilitaryDepartment Set end)
            }
        }

        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Faculty.Name CustomAttributes)

        // *** End programmer edit section *** (Faculty.Name CustomAttributes)
        [NotNull()]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Faculty.Name Get start)

                // *** End programmer edit section *** (Faculty.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Faculty.Name Get end)

                // *** End programmer edit section *** (Faculty.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Faculty.Name Set start)

                // *** End programmer edit section *** (Faculty.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Faculty.Name Set end)

                // *** End programmer edit section *** (Faculty.Name Set end)
            }
        }

        /// <summary>
        /// Профиль факультета.
        /// </summary>
        // *** Start programmer edit section *** (Faculty.Type CustomAttributes)

        // *** End programmer edit section *** (Faculty.Type CustomAttributes)
        public virtual tFacultyType Type
        {
            get
            {
                // *** Start programmer edit section *** (Faculty.Type Get start)

                // *** End programmer edit section *** (Faculty.Type Get start)
                tFacultyType result = this.fType;
                // *** Start programmer edit section *** (Faculty.Type Get end)

                // *** End programmer edit section *** (Faculty.Type Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Faculty.Type Set start)

                // *** End programmer edit section *** (Faculty.Type Set start)
                this.fType = value;
                // *** Start programmer edit section *** (Faculty.Type Set end)

                // *** End programmer edit section *** (Faculty.Type Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Faculty.Department CustomAttributes)

        // *** End programmer edit section *** (Faculty.Department CustomAttributes)
        [PropertyStorage(new string[] {
                "Faculty"})]
        public virtual Qwe.DetailArrayOfDepartment Department
        {
            get
            {
                // *** Start programmer edit section *** (Faculty.Department Get start)

                // *** End programmer edit section *** (Faculty.Department Get start)
                if ((this.fDepartment == null))
                {
                    this.fDepartment = new Qwe.DetailArrayOfDepartment(this);
                }
                Qwe.DetailArrayOfDepartment result = this.fDepartment;
                // *** Start programmer edit section *** (Faculty.Department Get end)

                // *** End programmer edit section *** (Faculty.Department Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Faculty.Department Set start)

                // *** End programmer edit section *** (Faculty.Department Set start)
                this.fDepartment = value;
                // *** Start programmer edit section *** (Faculty.Department Set end)

                // *** End programmer edit section *** (Faculty.Department Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Faculty.StudentBrigades CustomAttributes)

        // *** End programmer edit section *** (Faculty.StudentBrigades CustomAttributes)
        [PropertyStorage(new string[] {
                "Faculty"})]
        public virtual Qwe.DetailArrayOfStudentBrigades StudentBrigades
        {
            get
            {
                // *** Start programmer edit section *** (Faculty.StudentBrigades Get start)

                // *** End programmer edit section *** (Faculty.StudentBrigades Get start)
                if ((this.fStudentBrigades == null))
                {
                    this.fStudentBrigades = new Qwe.DetailArrayOfStudentBrigades(this);
                }
                Qwe.DetailArrayOfStudentBrigades result = this.fStudentBrigades;
                // *** Start programmer edit section *** (Faculty.StudentBrigades Get end)

                // *** End programmer edit section *** (Faculty.StudentBrigades Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Faculty.StudentBrigades Set start)

                // *** End programmer edit section *** (Faculty.StudentBrigades Set start)
                this.fStudentBrigades = value;
                // *** Start programmer edit section *** (Faculty.StudentBrigades Set end)

                // *** End programmer edit section *** (Faculty.StudentBrigades Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "FacultyE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FacultyE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FacultyE", typeof(Qwe.Faculty));
                }
            }

            /// <summary>
            /// "FacultyL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FacultyL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FacultyL", typeof(Qwe.Faculty));
                }
            }
        }

    }
}
