//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qwe
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Занятие.
    /// </summary>
    // *** Start programmer edit section *** (Lesson CustomAttributes)

    // *** End programmer edit section *** (Lesson CustomAttributes)
    [AutoAltered()]
    [Caption("Занятие")]
    [View("LessonD", new string[] {
            "Schedule as \'Расписание\'",
            "Subject as \'Предмет\'",
            "StartTime as \'Время начала\'",
            "EndTime as \'Время окончания\'",
            "Comment as \'Комментарий\'",
            "Teacher as \'Преподаватель\'",
            "Teacher.FullName",
            "Audience as \'Аудитория\'",
            "Audience.Name"}, Hidden=new string[] {
            "Schedule",
            "Teacher.FullName",
            "Audience.Name"})]
    [View("LessonL", new string[] {
            "Schedule",
            "Schedule.Year",
            "Schedule.Week",
            "Schedule.Day",
            "Schedule.DateFrom as \'Дата\'",
            "Subject as \'Предмет\'",
            "StartTime as \'Время начала\'",
            "EndTime as \'Время окончания\'",
            "Teacher.FullName as \'Преподаватель\'",
            "Audience.Name as \'Аудитория\'",
            "Comment as \'Комментарий\'"}, Hidden=new string[] {
            "Schedule",
            "Schedule.Year",
            "Schedule.Week",
            "Schedule.Day"})]
    public class Lesson : ICSSoft.STORMNET.DataObject
    {

        private string fComment;

        private System.DateTime fEndTime;

        private System.DateTime fStartTime;

        private string fSubject;

        private Qwe.Audience fAudience;

        private Qwe.Schedule fSchedule;

        private Qwe.Teacher fTeacher;

        // *** Start programmer edit section *** (Lesson CustomMembers)

        // *** End programmer edit section *** (Lesson CustomMembers)


        /// <summary>
        /// Комментарий.
        /// </summary>
        // *** Start programmer edit section *** (Lesson.Comment CustomAttributes)

        // *** End programmer edit section *** (Lesson.Comment CustomAttributes)
        public virtual string Comment
        {
            get
            {
                // *** Start programmer edit section *** (Lesson.Comment Get start)

                // *** End programmer edit section *** (Lesson.Comment Get start)
                string result = this.fComment;
                // *** Start programmer edit section *** (Lesson.Comment Get end)

                // *** End programmer edit section *** (Lesson.Comment Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lesson.Comment Set start)

                // *** End programmer edit section *** (Lesson.Comment Set start)
                this.fComment = value;
                // *** Start programmer edit section *** (Lesson.Comment Set end)

                // *** End programmer edit section *** (Lesson.Comment Set end)
            }
        }

        /// <summary>
        /// Время окончания.
        /// </summary>
        // *** Start programmer edit section *** (Lesson.EndTime CustomAttributes)

        // *** End programmer edit section *** (Lesson.EndTime CustomAttributes)
        [NotNull()]
        public virtual System.DateTime EndTime
        {
            get
            {
                // *** Start programmer edit section *** (Lesson.EndTime Get start)

                // *** End programmer edit section *** (Lesson.EndTime Get start)
                System.DateTime result = this.fEndTime;
                // *** Start programmer edit section *** (Lesson.EndTime Get end)

                // *** End programmer edit section *** (Lesson.EndTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lesson.EndTime Set start)

                // *** End programmer edit section *** (Lesson.EndTime Set start)
                this.fEndTime = value;
                // *** Start programmer edit section *** (Lesson.EndTime Set end)

                // *** End programmer edit section *** (Lesson.EndTime Set end)
            }
        }

        /// <summary>
        /// Время начала.
        /// </summary>
        // *** Start programmer edit section *** (Lesson.StartTime CustomAttributes)

        // *** End programmer edit section *** (Lesson.StartTime CustomAttributes)
        [NotNull()]
        public virtual System.DateTime StartTime
        {
            get
            {
                // *** Start programmer edit section *** (Lesson.StartTime Get start)

                // *** End programmer edit section *** (Lesson.StartTime Get start)
                System.DateTime result = this.fStartTime;
                // *** Start programmer edit section *** (Lesson.StartTime Get end)

                // *** End programmer edit section *** (Lesson.StartTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lesson.StartTime Set start)

                // *** End programmer edit section *** (Lesson.StartTime Set start)
                this.fStartTime = value;
                // *** Start programmer edit section *** (Lesson.StartTime Set end)

                // *** End programmer edit section *** (Lesson.StartTime Set end)
            }
        }

        /// <summary>
        /// Тема занятия.
        /// </summary>
        // *** Start programmer edit section *** (Lesson.Subject CustomAttributes)

        // *** End programmer edit section *** (Lesson.Subject CustomAttributes)
        public virtual string Subject
        {
            get
            {
                // *** Start programmer edit section *** (Lesson.Subject Get start)

                // *** End programmer edit section *** (Lesson.Subject Get start)
                string result = this.fSubject;
                // *** Start programmer edit section *** (Lesson.Subject Get end)

                // *** End programmer edit section *** (Lesson.Subject Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lesson.Subject Set start)

                // *** End programmer edit section *** (Lesson.Subject Set start)
                this.fSubject = value;
                // *** Start programmer edit section *** (Lesson.Subject Set end)

                // *** End programmer edit section *** (Lesson.Subject Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Lesson.Audience CustomAttributes)

        // *** End programmer edit section *** (Lesson.Audience CustomAttributes)
        [PropertyStorage(new string[] {
                "Audience"})]
        public virtual Qwe.Audience Audience
        {
            get
            {
                // *** Start programmer edit section *** (Lesson.Audience Get start)

                // *** End programmer edit section *** (Lesson.Audience Get start)
                Qwe.Audience result = this.fAudience;
                // *** Start programmer edit section *** (Lesson.Audience Get end)

                // *** End programmer edit section *** (Lesson.Audience Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lesson.Audience Set start)

                // *** End programmer edit section *** (Lesson.Audience Set start)
                this.fAudience = value;
                // *** Start programmer edit section *** (Lesson.Audience Set end)

                // *** End programmer edit section *** (Lesson.Audience Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Lesson.Schedule CustomAttributes)

        // *** End programmer edit section *** (Lesson.Schedule CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Schedule"})]
        public virtual Qwe.Schedule Schedule
        {
            get
            {
                // *** Start programmer edit section *** (Lesson.Schedule Get start)

                // *** End programmer edit section *** (Lesson.Schedule Get start)
                Qwe.Schedule result = this.fSchedule;
                // *** Start programmer edit section *** (Lesson.Schedule Get end)

                // *** End programmer edit section *** (Lesson.Schedule Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lesson.Schedule Set start)

                // *** End programmer edit section *** (Lesson.Schedule Set start)
                this.fSchedule = value;
                // *** Start programmer edit section *** (Lesson.Schedule Set end)

                // *** End programmer edit section *** (Lesson.Schedule Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Lesson.Teacher CustomAttributes)

        // *** End programmer edit section *** (Lesson.Teacher CustomAttributes)
        [NotNull()]
        [PropertyStorage(new string[] {
                "Teacher"})]
        public virtual Qwe.Teacher Teacher
        {
            get
            {
                // *** Start programmer edit section *** (Lesson.Teacher Get start)

                // *** End programmer edit section *** (Lesson.Teacher Get start)
                Qwe.Teacher result = this.fTeacher;
                // *** Start programmer edit section *** (Lesson.Teacher Get end)

                // *** End programmer edit section *** (Lesson.Teacher Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Lesson.Teacher Set start)

                // *** End programmer edit section *** (Lesson.Teacher Set start)
                this.fTeacher = value;
                // *** Start programmer edit section *** (Lesson.Teacher Set end)

                // *** End programmer edit section *** (Lesson.Teacher Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "LessonD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LessonD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LessonD", typeof(Qwe.Lesson));
                }
            }

            /// <summary>
            /// "LessonL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View LessonL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("LessonL", typeof(Qwe.Lesson));
                }
            }
        }

    }

    /// <summary>
    /// Detail array of Lesson.
    /// </summary>
    public class DetailArrayOfLesson : ICSSoft.STORMNET.DetailArray
    {
        /// <summary>
        /// Construct detail array.
        /// </summary>
        public DetailArrayOfLesson(Qwe.Schedule fSchedule) :
                base(typeof(Lesson), ((ICSSoft.STORMNET.DataObject)(fSchedule)))
        {
        }

        /// <summary>
        /// Returns object with type Lesson by index.
        /// </summary>
        public Qwe.Lesson this[int index]
        {
            get
            {
                return ((Qwe.Lesson)(this.ItemByIndex(index)));
            }
        }

        /// <summary>
        /// Adds object with type Lesson.
        /// </summary>
        public virtual void Add(Qwe.Lesson dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
