//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe
{
    /// <summary>
    /// Class for determinate objects assembly in DI.
    /// </summary>
    public class ObjectsMarker
    {
    }
}
