//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qwe
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// .
    /// </summary>
    // *** Start programmer edit section *** (ScheduleGroup CustomAttributes)

    // *** End programmer edit section *** (ScheduleGroup CustomAttributes)
    [AutoAltered()]
    [Caption("")]
    [View("ScheduleGroupD", new string[] {
            "Schedule as \'Расписание\'",
            "Schedule.Year",
            "Schedule.Week",
            "Schedule.Day",
            "Schedule.DateFrom",
            "Group as \'Группа\'",
            "Group.FullName as \'Полное назание группы\'",
            "Group.Name as \'Назание группы\'",
            "Group.EnrollmentYear",
            "Summary as \'Описание\'"}, Hidden=new string[] {
            "Schedule.Year",
            "Schedule.Week",
            "Schedule.Day",
            "Schedule.DateFrom",
            "Group.Name",
            "Group.EnrollmentYear"})]
    public class ScheduleGroup : ICSSoft.STORMNET.DataObject
    {

        private string fSummary;

        private Qwe.Group fGroup;

        private Qwe.Schedule fSchedule;

        // *** Start programmer edit section *** (ScheduleGroup CustomMembers)

        // *** End programmer edit section *** (ScheduleGroup CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (ScheduleGroup.Summary CustomAttributes)

        // *** End programmer edit section *** (ScheduleGroup.Summary CustomAttributes)
        public virtual string Summary
        {
            get
            {
                // *** Start programmer edit section *** (ScheduleGroup.Summary Get start)

                // *** End programmer edit section *** (ScheduleGroup.Summary Get start)
                string result = this.fSummary;
                // *** Start programmer edit section *** (ScheduleGroup.Summary Get end)

                // *** End programmer edit section *** (ScheduleGroup.Summary Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ScheduleGroup.Summary Set start)

                // *** End programmer edit section *** (ScheduleGroup.Summary Set start)
                this.fSummary = value;
                // *** Start programmer edit section *** (ScheduleGroup.Summary Set end)

                // *** End programmer edit section *** (ScheduleGroup.Summary Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (ScheduleGroup.Group CustomAttributes)

        // *** End programmer edit section *** (ScheduleGroup.Group CustomAttributes)
        [NotNull()]
        [PropertyStorage(new string[] {
                "Group"})]
        public virtual Qwe.Group Group
        {
            get
            {
                // *** Start programmer edit section *** (ScheduleGroup.Group Get start)

                // *** End programmer edit section *** (ScheduleGroup.Group Get start)
                Qwe.Group result = this.fGroup;
                // *** Start programmer edit section *** (ScheduleGroup.Group Get end)

                // *** End programmer edit section *** (ScheduleGroup.Group Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ScheduleGroup.Group Set start)

                // *** End programmer edit section *** (ScheduleGroup.Group Set start)
                this.fGroup = value;
                // *** Start programmer edit section *** (ScheduleGroup.Group Set end)

                // *** End programmer edit section *** (ScheduleGroup.Group Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (ScheduleGroup.Schedule CustomAttributes)

        // *** End programmer edit section *** (ScheduleGroup.Schedule CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Schedule"})]
        public virtual Qwe.Schedule Schedule
        {
            get
            {
                // *** Start programmer edit section *** (ScheduleGroup.Schedule Get start)

                // *** End programmer edit section *** (ScheduleGroup.Schedule Get start)
                Qwe.Schedule result = this.fSchedule;
                // *** Start programmer edit section *** (ScheduleGroup.Schedule Get end)

                // *** End programmer edit section *** (ScheduleGroup.Schedule Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ScheduleGroup.Schedule Set start)

                // *** End programmer edit section *** (ScheduleGroup.Schedule Set start)
                this.fSchedule = value;
                // *** Start programmer edit section *** (ScheduleGroup.Schedule Set end)

                // *** End programmer edit section *** (ScheduleGroup.Schedule Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ScheduleGroupD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ScheduleGroupD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ScheduleGroupD", typeof(Qwe.ScheduleGroup));
                }
            }
        }

    }

    /// <summary>
    /// Detail array of ScheduleGroup.
    /// </summary>
    public class DetailArrayOfScheduleGroup : ICSSoft.STORMNET.DetailArray
    {
        /// <summary>
        /// Construct detail array.
        /// </summary>
        public DetailArrayOfScheduleGroup(Qwe.Schedule fSchedule) :
                base(typeof(ScheduleGroup), ((ICSSoft.STORMNET.DataObject)(fSchedule)))
        {
        }

        /// <summary>
        /// Returns object with type ScheduleGroup by index.
        /// </summary>
        public Qwe.ScheduleGroup this[int index]
        {
            get
            {
                return ((Qwe.ScheduleGroup)(this.ItemByIndex(index)));
            }
        }

        /// <summary>
        /// Adds object with type ScheduleGroup.
        /// </summary>
        public virtual void Add(Qwe.ScheduleGroup dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
