//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qwe
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// СтудОтряды.
    /// </summary>
    // *** Start programmer edit section *** (StudentBrigades CustomAttributes)

    // *** End programmer edit section *** (StudentBrigades CustomAttributes)
    [AutoAltered()]
    [Caption("СтудОтряды")]
    [View("StudentBrigadesD", new string[] {
            "Participants as \'Участники\'",
            "Faculty as \'Факультет\'"}, Hidden=new string[] {
            "Faculty"})]
    public class StudentBrigades : ICSSoft.STORMNET.DataObject
    {

        private int fParticipants = 0;

        private Qwe.Faculty fFaculty;

        // *** Start programmer edit section *** (StudentBrigades CustomMembers)

        // *** End programmer edit section *** (StudentBrigades CustomMembers)


        /// <summary>
        /// участники.
        /// </summary>
        // *** Start programmer edit section *** (StudentBrigades.Participants CustomAttributes)

        // *** End programmer edit section *** (StudentBrigades.Participants CustomAttributes)
        [NotNull()]
        public virtual int Participants
        {
            get
            {
                // *** Start programmer edit section *** (StudentBrigades.Participants Get start)

                // *** End programmer edit section *** (StudentBrigades.Participants Get start)
                int result = this.fParticipants;
                // *** Start programmer edit section *** (StudentBrigades.Participants Get end)

                // *** End programmer edit section *** (StudentBrigades.Participants Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StudentBrigades.Participants Set start)

                // *** End programmer edit section *** (StudentBrigades.Participants Set start)
                this.fParticipants = value;
                // *** Start programmer edit section *** (StudentBrigades.Participants Set end)

                // *** End programmer edit section *** (StudentBrigades.Participants Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (StudentBrigades.Faculty CustomAttributes)

        // *** End programmer edit section *** (StudentBrigades.Faculty CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Faculty"})]
        public virtual Qwe.Faculty Faculty
        {
            get
            {
                // *** Start programmer edit section *** (StudentBrigades.Faculty Get start)

                // *** End programmer edit section *** (StudentBrigades.Faculty Get start)
                Qwe.Faculty result = this.fFaculty;
                // *** Start programmer edit section *** (StudentBrigades.Faculty Get end)

                // *** End programmer edit section *** (StudentBrigades.Faculty Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StudentBrigades.Faculty Set start)

                // *** End programmer edit section *** (StudentBrigades.Faculty Set start)
                this.fFaculty = value;
                // *** Start programmer edit section *** (StudentBrigades.Faculty Set end)

                // *** End programmer edit section *** (StudentBrigades.Faculty Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "StudentBrigadesD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StudentBrigadesD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StudentBrigadesD", typeof(Qwe.StudentBrigades));
                }
            }
        }

    }

    /// <summary>
    /// Detail array of StudentBrigades.
    /// </summary>
    public class DetailArrayOfStudentBrigades : ICSSoft.STORMNET.DetailArray
    {
        /// <summary>
        /// Construct detail array.
        /// </summary>
        public DetailArrayOfStudentBrigades(Qwe.Faculty fFaculty) :
                base(typeof(StudentBrigades), ((ICSSoft.STORMNET.DataObject)(fFaculty)))
        {
        }

        /// <summary>
        /// Returns object with type StudentBrigades by index.
        /// </summary>
        public Qwe.StudentBrigades this[int index]
        {
            get
            {
                return ((Qwe.StudentBrigades)(this.ItemByIndex(index)));
            }
        }

        /// <summary>
        /// Adds object with type StudentBrigades.
        /// </summary>
        public virtual void Add(Qwe.StudentBrigades dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
