//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qwe
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Учебный план.
    /// </summary>
    // *** Start programmer edit section *** (StudyPlan CustomAttributes)

    // *** End programmer edit section *** (StudyPlan CustomAttributes)
    [AutoAltered()]
    [Caption("Учебный план")]
    [View("StudyPlanE", new string[] {
            "CreationDate as \'Дата создания\'",
            "HasPractice as \'Наличие практики\'",
            "Specialization as \'Специализация\'",
            "TotalHours as \'Количество часов\'"})]
    [View("StudyPlanL", new string[] {
            "CreationDate as \'Дата создания\'",
            "HasPractice as \'Наличие практики\'",
            "Specialization as \'Специализация\'",
            "TotalHours as \'Количество часов\'"})]
    public class StudyPlan : ICSSoft.STORMNET.DataObject
    {

        private System.DateTime fCreationDate = DateTime.Now;

        private bool fHasPractice = false;

        private string fSpecialization;

        private int fTotalHours = 0;

        // *** Start programmer edit section *** (StudyPlan CustomMembers)

        // *** End programmer edit section *** (StudyPlan CustomMembers)


        /// <summary>
        /// Дата создания.
        /// </summary>
        // *** Start programmer edit section *** (StudyPlan.CreationDate CustomAttributes)

        // *** End programmer edit section *** (StudyPlan.CreationDate CustomAttributes)
        [NotNull()]
        public virtual System.DateTime CreationDate
        {
            get
            {
                // *** Start programmer edit section *** (StudyPlan.CreationDate Get start)

                // *** End programmer edit section *** (StudyPlan.CreationDate Get start)
                System.DateTime result = this.fCreationDate;
                // *** Start programmer edit section *** (StudyPlan.CreationDate Get end)

                // *** End programmer edit section *** (StudyPlan.CreationDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StudyPlan.CreationDate Set start)

                // *** End programmer edit section *** (StudyPlan.CreationDate Set start)
                this.fCreationDate = value;
                // *** Start programmer edit section *** (StudyPlan.CreationDate Set end)

                // *** End programmer edit section *** (StudyPlan.CreationDate Set end)
            }
        }

        /// <summary>
        /// Наличие практики.
        /// </summary>
        // *** Start programmer edit section *** (StudyPlan.HasPractice CustomAttributes)

        // *** End programmer edit section *** (StudyPlan.HasPractice CustomAttributes)
        [NotNull()]
        public virtual bool HasPractice
        {
            get
            {
                // *** Start programmer edit section *** (StudyPlan.HasPractice Get start)

                // *** End programmer edit section *** (StudyPlan.HasPractice Get start)
                bool result = this.fHasPractice;
                // *** Start programmer edit section *** (StudyPlan.HasPractice Get end)

                // *** End programmer edit section *** (StudyPlan.HasPractice Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StudyPlan.HasPractice Set start)

                // *** End programmer edit section *** (StudyPlan.HasPractice Set start)
                this.fHasPractice = value;
                // *** Start programmer edit section *** (StudyPlan.HasPractice Set end)

                // *** End programmer edit section *** (StudyPlan.HasPractice Set end)
            }
        }

        /// <summary>
        /// Специализация.
        /// </summary>
        // *** Start programmer edit section *** (StudyPlan.Specialization CustomAttributes)

        // *** End programmer edit section *** (StudyPlan.Specialization CustomAttributes)
        public virtual string Specialization
        {
            get
            {
                // *** Start programmer edit section *** (StudyPlan.Specialization Get start)

                // *** End programmer edit section *** (StudyPlan.Specialization Get start)
                string result = this.fSpecialization;
                // *** Start programmer edit section *** (StudyPlan.Specialization Get end)

                // *** End programmer edit section *** (StudyPlan.Specialization Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StudyPlan.Specialization Set start)

                // *** End programmer edit section *** (StudyPlan.Specialization Set start)
                this.fSpecialization = value;
                // *** Start programmer edit section *** (StudyPlan.Specialization Set end)

                // *** End programmer edit section *** (StudyPlan.Specialization Set end)
            }
        }

        /// <summary>
        /// Количество часов.
        /// </summary>
        // *** Start programmer edit section *** (StudyPlan.TotalHours CustomAttributes)

        // *** End programmer edit section *** (StudyPlan.TotalHours CustomAttributes)
        [NotNull()]
        public virtual int TotalHours
        {
            get
            {
                // *** Start programmer edit section *** (StudyPlan.TotalHours Get start)

                // *** End programmer edit section *** (StudyPlan.TotalHours Get start)
                int result = this.fTotalHours;
                // *** Start programmer edit section *** (StudyPlan.TotalHours Get end)

                // *** End programmer edit section *** (StudyPlan.TotalHours Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (StudyPlan.TotalHours Set start)

                // *** End programmer edit section *** (StudyPlan.TotalHours Set start)
                this.fTotalHours = value;
                // *** Start programmer edit section *** (StudyPlan.TotalHours Set end)

                // *** End programmer edit section *** (StudyPlan.TotalHours Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "StudyPlanE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StudyPlanE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StudyPlanE", typeof(Qwe.StudyPlan));
                }
            }

            /// <summary>
            /// "StudyPlanL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StudyPlanL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StudyPlanL", typeof(Qwe.StudyPlan));
                }
            }
        }

    }
}
