//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qwe
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Преподаватель.
    /// </summary>
    // *** Start programmer edit section *** (Teacher CustomAttributes)

    // *** End programmer edit section *** (Teacher CustomAttributes)
    [AutoAltered()]
    [Caption("Преподаватель")]
    [View("TeacherE", new string[] {
            "DateOfBirth as \'Дата рождения\'",
            "Degree as \'Научная степень\'",
            "FullName as \'ФИО\'",
            "PartTime as \'Совместитель\'",
            "StudyPlan as \'Учебный план\'",
            "StudyPlan.Specialization as \'Специализация\'"}, Hidden=new string[] {
            "StudyPlan.Specialization"})]
    [View("TeacherL", new string[] {
            "DateOfBirth as \'Дата рождения\'",
            "Degree as \'Научная степень\'",
            "FullName as \'ФИО\'",
            "PartTime as \'Совместитель\'"}, Hidden=new string[] {
            "StudyPlan.Specialization"})]
    public class Teacher : ICSSoft.STORMNET.DataObject
    {

        private System.DateTime fDateOfBirth = DateTime.Now;

        private tAcademicDegree fDegree;

        private string fFullName;

        private bool fPartTime = false;

        private Qwe.StudyPlan fStudyPlan;

        // *** Start programmer edit section *** (Teacher CustomMembers)

        // *** End programmer edit section *** (Teacher CustomMembers)


        /// <summary>
        /// Дата рождения.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.DateOfBirth CustomAttributes)

        // *** End programmer edit section *** (Teacher.DateOfBirth CustomAttributes)
        [NotNull()]
        public virtual System.DateTime DateOfBirth
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.DateOfBirth Get start)

                // *** End programmer edit section *** (Teacher.DateOfBirth Get start)
                System.DateTime result = this.fDateOfBirth;
                // *** Start programmer edit section *** (Teacher.DateOfBirth Get end)

                // *** End programmer edit section *** (Teacher.DateOfBirth Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.DateOfBirth Set start)

                // *** End programmer edit section *** (Teacher.DateOfBirth Set start)
                this.fDateOfBirth = value;
                // *** Start programmer edit section *** (Teacher.DateOfBirth Set end)

                // *** End programmer edit section *** (Teacher.DateOfBirth Set end)
            }
        }

        /// <summary>
        /// Научная степень.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.Degree CustomAttributes)

        // *** End programmer edit section *** (Teacher.Degree CustomAttributes)
        public virtual tAcademicDegree Degree
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.Degree Get start)

                // *** End programmer edit section *** (Teacher.Degree Get start)
                tAcademicDegree result = this.fDegree;
                // *** Start programmer edit section *** (Teacher.Degree Get end)

                // *** End programmer edit section *** (Teacher.Degree Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.Degree Set start)

                // *** End programmer edit section *** (Teacher.Degree Set start)
                this.fDegree = value;
                // *** Start programmer edit section *** (Teacher.Degree Set end)

                // *** End programmer edit section *** (Teacher.Degree Set end)
            }
        }

        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.FullName CustomAttributes)

        // *** End programmer edit section *** (Teacher.FullName CustomAttributes)
        public virtual string FullName
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.FullName Get start)

                // *** End programmer edit section *** (Teacher.FullName Get start)
                string result = this.fFullName;
                // *** Start programmer edit section *** (Teacher.FullName Get end)

                // *** End programmer edit section *** (Teacher.FullName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.FullName Set start)

                // *** End programmer edit section *** (Teacher.FullName Set start)
                this.fFullName = value;
                // *** Start programmer edit section *** (Teacher.FullName Set end)

                // *** End programmer edit section *** (Teacher.FullName Set end)
            }
        }

        /// <summary>
        /// Совместитель.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.PartTime CustomAttributes)

        // *** End programmer edit section *** (Teacher.PartTime CustomAttributes)
        [NotNull()]
        public virtual bool PartTime
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.PartTime Get start)

                // *** End programmer edit section *** (Teacher.PartTime Get start)
                bool result = this.fPartTime;
                // *** Start programmer edit section *** (Teacher.PartTime Get end)

                // *** End programmer edit section *** (Teacher.PartTime Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.PartTime Set start)

                // *** End programmer edit section *** (Teacher.PartTime Set start)
                this.fPartTime = value;
                // *** Start programmer edit section *** (Teacher.PartTime Set end)

                // *** End programmer edit section *** (Teacher.PartTime Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (Teacher.StudyPlan CustomAttributes)

        // *** End programmer edit section *** (Teacher.StudyPlan CustomAttributes)
        [PropertyStorage(new string[] {
                "StudyPlan"})]
        public virtual Qwe.StudyPlan StudyPlan
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.StudyPlan Get start)

                // *** End programmer edit section *** (Teacher.StudyPlan Get start)
                Qwe.StudyPlan result = this.fStudyPlan;
                // *** Start programmer edit section *** (Teacher.StudyPlan Get end)

                // *** End programmer edit section *** (Teacher.StudyPlan Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.StudyPlan Set start)

                // *** End programmer edit section *** (Teacher.StudyPlan Set start)
                this.fStudyPlan = value;
                // *** Start programmer edit section *** (Teacher.StudyPlan Set end)

                // *** End programmer edit section *** (Teacher.StudyPlan Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "TeacherE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeacherE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeacherE", typeof(Qwe.Teacher));
                }
            }

            /// <summary>
            /// "TeacherL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeacherL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeacherL", typeof(Qwe.Teacher));
                }
            }
        }

    }
}
