//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qwe
{
    using System.ComponentModel;
    using System.Text.Json.Serialization;
    using ICSSoft.STORMNET;

    /// <summary>
    /// .
    /// </summary>
    [TypeConverter(typeof(CaptionEnumConverter))]
    [JsonConverter(typeof(JsonCaptionEnumConverterFactory))]
    public enum tStudentStatus
    {

        [Caption("Академический отпуск")]
        AcademicLeave,

        [Caption("Обучается")]
        Active,

        [Caption("Отчислен")]
        Expelled,

        [Caption("Выпущен")]
        Graduated,
    }
}
