//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Student
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Student.StudentL.
    /// </summary>
    [DataView(typeof(Student), "StudentL")]
    public partial class StudentLDto : StudentDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="StudentLDto"/>.
        /// </summary>
        public StudentLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="StudentLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public StudentLDto(Student source)
        {
            FillFromClass(source);
        }

        /// <summary>
        /// Дата зачисления.
        /// </summary>
        [PropertyName("EnrollmentDate")]
        [CaptionProperty("Дата зачисления")]
        public DateTime EnrollmentDate { get; set; } = DateTime.Now;

                /// <summary>
        /// ФИО.
        /// </summary>
        [PropertyName("FullName")]
        [CaptionProperty("ФИО")]
        public string FullName { get; set; } = string.Empty;

        /// <summary>
        /// Бюджетная основа.
        /// </summary>
        [PropertyName("IsBudget")]
        [CaptionProperty("Бюджетная основа")]
        public bool IsBudget { get; set; } = false;

        /// <summary>
        /// Статус.
        /// </summary>
        [PropertyName("Status")]
        [CaptionProperty("Статус")]
        public tStudentStatus Status { get; set; }

                /// <summary>
        /// Номер зачётной книжки .
        /// </summary>
        [PropertyName("StudentId")]
        [CaptionProperty("Номер зачётной книжки ")]
        public string StudentId { get; set; } = string.Empty;

        /// <summary>
        /// Plan.HasPractice.
        /// </summary>
        [PropertyName("Plan.HasPractice")]
        [CaptionProperty("")]
        public bool? PlanHasPractice { get; set; } = false;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override StudentLDto FillFromClass(Student source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            EnrollmentDate = source.EnrollmentDate.ToUniversalTime();
            FullName = source.FullName;
            IsBudget = source.IsBudget;
            Status = source.Status;
            StudentId = source.StudentId;
            PlanHasPractice = source.Plan?.HasPractice;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Student destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.EnrollmentDate = EnrollmentDate.ToUniversalTime();
            destination.FullName = FullName;
            destination.IsBudget = IsBudget;
            destination.Status = Status;
            destination.StudentId = StudentId;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
