//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Student
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Qwe;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации StudentL.
    /// </summary>
    public partial class StudentLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StudentLFilterDto"/> class.
        /// </summary>
        public StudentLFilterDto()
        {
            DtoType = typeof(StudentLDto);
        }

        /// <summary>
        /// Дата зачисления.
        /// </summary>
        public DateTime? EnrollmentDate { get; set; }

        /// <summary>
        /// Дата зачисления.
        /// </summary>
        public FilterOperation? EnrollmentDateOp { get; set; }
        /// <summary>
        /// ФИО.
        /// </summary>
        public string? FullName { get; set; }

        /// <summary>
        /// ФИО.
        /// </summary>
        public FilterOperation? FullNameOp { get; set; }
        /// <summary>
        /// Бюджетная основа.
        /// </summary>
        public bool? IsBudget { get; set; }

        /// <summary>
        /// Бюджетная основа.
        /// </summary>
        public FilterOperation? IsBudgetOp { get; set; }
        /// <summary>
        /// Статус.
        /// </summary>
        public tStudentStatus? Status { get; set; }

        /// <summary>
        /// Статус.
        /// </summary>
        public FilterOperation? StatusOp { get; set; }
        /// <summary>
        /// Номер зачётной книжки .
        /// </summary>
        public string? StudentId { get; set; }

        /// <summary>
        /// Номер зачётной книжки .
        /// </summary>
        public FilterOperation? StudentIdOp { get; set; }
        /// <summary>
        /// .
        /// </summary>
        public bool? PlanHasPractice { get; set; }

        /// <summary>
        /// .
        /// </summary>
        public FilterOperation? PlanHasPracticeOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (EnrollmentDateOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Student>(EnrollmentDateOp.Value, d => d.EnrollmentDate, EnrollmentDate));
            }

            if (FullNameOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Student>(FullNameOp.Value, d => d.FullName, FullName));
            }

            if (IsBudgetOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Student>(IsBudgetOp.Value, d => d.IsBudget, IsBudget));
            }

            if (StatusOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Student>(StatusOp.Value, d => d.Status, Status));
            }

            if (StudentIdOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Student>(StudentIdOp.Value, d => d.StudentId, StudentId));
            }

            if (PlanHasPracticeOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Student>(PlanHasPracticeOp.Value, d => d.Plan.HasPractice, PlanHasPractice));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
