//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { DepartmentService } from '@/services/Department.service';

const useDeleteAllDepartment = (onSuccess: (result: string[]) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAllDepartment,
    mutateAsync: deleteAllDepartmentAsync,
    isPending,
  } = useMutation({
    mutationFn: (ids: string[]) => DepartmentService.DeleteAllDepartment(ids),
    onSuccess: (_, ids) => {
      const className = 'department';
      ids.forEach((id) => {
        queryClient.removeQueries({ queryKey: [className, id] });
      });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(ids);
    },
    onError: (e) => onError(e),
  });

  return { deleteAllDepartment, deleteAllDepartmentAsync, isPending };
};

export default useDeleteAllDepartment;
