//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { ScheduleGroupService } from '@/services/ScheduleGroup.service';
import { IBaseScheduleGroup } from '@/types/ScheduleGroup.types';

const useCreateScheduleGroup = <T extends IBaseScheduleGroup>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type CreateRecordArgs = {
    scheduleGroup: T;
    viewName: string;
  };

  const {
    mutate: createScheduleGroup,
    mutateAsync: createScheduleGroupAsync,
    isPending,
  } = useMutation({
    mutationFn: (createRecordArgs: CreateRecordArgs) =>
      ScheduleGroupService.CreateScheduleGroup<T>(createRecordArgs.scheduleGroup, createRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'scheduleGroup';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { createScheduleGroup, createScheduleGroupAsync, isPending };
};

export default useCreateScheduleGroup;
