//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { ScheduleGroupService } from '@/services/ScheduleGroup.service';

const useDeleteScheduleGroup = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteScheduleGroup,
    mutateAsync: deleteScheduleGroupAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => ScheduleGroupService.DeleteScheduleGroup(id),
    onSuccess: (_, id) => {
      const className = 'scheduleGroup';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteScheduleGroup, deleteScheduleGroupAsync, isPending };
};

export default useDeleteScheduleGroup;
