//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';

import { ScheduleGroupService } from '@/services/ScheduleGroup.service';
import { IBaseScheduleGroup } from '@/types/ScheduleGroup.types';
import { GetAllRequestResult } from '@/types/helpers/GetAllRequestResult';
import { GetAllRequestOptions } from '@/types/helpers/GetAllRequestOptions';

const useGetAllScheduleGroup = <T extends IBaseScheduleGroup>({
  viewName,
  perPage,
  page,
  sorting,
  filter,
  search,
  enabled = true,
}: GetAllRequestOptions) => {
  const [isTriggered, setIsTriggered] = useState(false);

  const { data, isFetching, isError } = useQuery({
    queryKey: ['scheduleGroup', 'list', viewName, { perPage, page, sorting, filter, search }],
    retry: false,
    enabled: isTriggered || enabled,
    placeholderData: (prev) => prev,
    queryFn: async (): Promise<GetAllRequestResult<T>> => {
      const response = await ScheduleGroupService.GetAllScheduleGroup(viewName, perPage, page, sorting, filter, search);
      return response.data;
    },
  });

  const trigger = () => {
    setIsTriggered(true);
  };

  return {
    data: data?.records || [],
    count: data?.count || 0,
    isLoading: isFetching,
    isError,
    trigger,
  };
};

export default useGetAllScheduleGroup;
