//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Teacher
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Teacher.TeacherL.
    /// </summary>
    [DataView(typeof(Teacher), "TeacherL")]
    public partial class TeacherLDto : TeacherDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="TeacherLDto"/>.
        /// </summary>
        public TeacherLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="TeacherLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public TeacherLDto(Teacher source)
        {
            FillFromClass(source);
        }

        /// <summary>
        /// Дата рождения.
        /// </summary>
        [PropertyName("DateOfBirth")]
        [CaptionProperty("Дата рождения")]
        public DateTime DateOfBirth { get; set; } = DateTime.Now;

        /// <summary>
        /// Научная степень.
        /// </summary>
        [PropertyName("Degree")]
        [CaptionProperty("Научная степень")]
        public tAcademicDegree Degree { get; set; }

                /// <summary>
        /// ФИО.
        /// </summary>
        [PropertyName("FullName")]
        [CaptionProperty("ФИО")]
        public string FullName { get; set; } = string.Empty;

        /// <summary>
        /// Совместитель.
        /// </summary>
        [PropertyName("PartTime")]
        [CaptionProperty("Совместитель")]
        public bool PartTime { get; set; } = false;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override TeacherLDto FillFromClass(Teacher source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            DateOfBirth = source.DateOfBirth.ToUniversalTime();
            Degree = source.Degree;
            FullName = source.FullName;
            PartTime = source.PartTime;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Teacher destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.DateOfBirth = DateOfBirth.ToUniversalTime();
            destination.Degree = Degree;
            destination.FullName = FullName;
            destination.PartTime = PartTime;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
