//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Teacher
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Qwe;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации TeacherL.
    /// </summary>
    public partial class TeacherLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TeacherLFilterDto"/> class.
        /// </summary>
        public TeacherLFilterDto()
        {
            DtoType = typeof(TeacherLDto);
        }

        /// <summary>
        /// Дата рождения.
        /// </summary>
        public DateTime? DateOfBirth { get; set; }

        /// <summary>
        /// Дата рождения.
        /// </summary>
        public FilterOperation? DateOfBirthOp { get; set; }
        /// <summary>
        /// Научная степень.
        /// </summary>
        public tAcademicDegree? Degree { get; set; }

        /// <summary>
        /// Научная степень.
        /// </summary>
        public FilterOperation? DegreeOp { get; set; }
        /// <summary>
        /// ФИО.
        /// </summary>
        public string? FullName { get; set; }

        /// <summary>
        /// ФИО.
        /// </summary>
        public FilterOperation? FullNameOp { get; set; }
        /// <summary>
        /// Совместитель.
        /// </summary>
        public bool? PartTime { get; set; }

        /// <summary>
        /// Совместитель.
        /// </summary>
        public FilterOperation? PartTimeOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (DateOfBirthOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Teacher>(DateOfBirthOp.Value, d => d.DateOfBirth, DateOfBirth));
            }

            if (DegreeOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Teacher>(DegreeOp.Value, d => d.Degree, Degree));
            }

            if (FullNameOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Teacher>(FullNameOp.Value, d => d.FullName, FullName));
            }

            if (PartTimeOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Teacher>(PartTimeOp.Value, d => d.PartTime, PartTime));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
