//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.StudyPlan
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Qwe;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации StudyPlanL.
    /// </summary>
    public partial class StudyPlanLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StudyPlanLFilterDto"/> class.
        /// </summary>
        public StudyPlanLFilterDto()
        {
            DtoType = typeof(StudyPlanLDto);
        }

        /// <summary>
        /// Дата создания.
        /// </summary>
        public DateTime? CreationDate { get; set; }

        /// <summary>
        /// Дата создания.
        /// </summary>
        public FilterOperation? CreationDateOp { get; set; }
        /// <summary>
        /// Наличие практики.
        /// </summary>
        public bool? HasPractice { get; set; }

        /// <summary>
        /// Наличие практики.
        /// </summary>
        public FilterOperation? HasPracticeOp { get; set; }
        /// <summary>
        /// Специализация.
        /// </summary>
        public string? Specialization { get; set; }

        /// <summary>
        /// Специализация.
        /// </summary>
        public FilterOperation? SpecializationOp { get; set; }
        /// <summary>
        /// Количество часов.
        /// </summary>
        public int? TotalHours { get; set; }

        /// <summary>
        /// Количество часов.
        /// </summary>
        public FilterOperation? TotalHoursOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (CreationDateOp != null)
            {
                limitFunctions.Add(GetFilterFunction<StudyPlan>(CreationDateOp.Value, d => d.CreationDate, CreationDate));
            }

            if (HasPracticeOp != null)
            {
                limitFunctions.Add(GetFilterFunction<StudyPlan>(HasPracticeOp.Value, d => d.HasPractice, HasPractice));
            }

            if (SpecializationOp != null)
            {
                limitFunctions.Add(GetFilterFunction<StudyPlan>(SpecializationOp.Value, d => d.Specialization, Specialization));
            }

            if (TotalHoursOp != null)
            {
                limitFunctions.Add(GetFilterFunction<StudyPlan>(TotalHoursOp.Value, d => d.TotalHours, TotalHours));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
