//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.StudyPlan
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления StudyPlan.StudyPlanE.
    /// </summary>
    [DataView(typeof(StudyPlan), "StudyPlanE")]
    public partial class StudyPlanEDto : StudyPlanDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="StudyPlanEDto"/>.
        /// </summary>
        public StudyPlanEDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="StudyPlanEDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public StudyPlanEDto(StudyPlan source)
        {
            FillFromClass(source);
        }

        /// <summary>
        /// Дата создания.
        /// </summary>
        [PropertyName("CreationDate")]
        [CaptionProperty("Дата создания")]
        public DateTime CreationDate { get; set; } = DateTime.Now;

        /// <summary>
        /// Наличие практики.
        /// </summary>
        [PropertyName("HasPractice")]
        [CaptionProperty("Наличие практики")]
        public bool HasPractice { get; set; } = false;

                /// <summary>
        /// Специализация.
        /// </summary>
        [PropertyName("Specialization")]
        [CaptionProperty("Специализация")]
        public string Specialization { get; set; } = string.Empty;

        /// <summary>
        /// Количество часов.
        /// </summary>
        [PropertyName("TotalHours")]
        [CaptionProperty("Количество часов")]
        public int TotalHours { get; set; } = 0;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override StudyPlanEDto FillFromClass(StudyPlan source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            CreationDate = source.CreationDate.ToUniversalTime();
            HasPractice = source.HasPractice;
            Specialization = source.Specialization;
            TotalHours = source.TotalHours;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(StudyPlan destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.CreationDate = CreationDate.ToUniversalTime();
            destination.HasPractice = HasPractice;
            destination.Specialization = Specialization;
            destination.TotalHours = TotalHours;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
