//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Department
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Department.AuditView.
    /// </summary>
    [DataView(typeof(Department), "AuditView")]
    public partial class AuditViewDto : DepartmentDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AuditViewDto"/>.
        /// </summary>
        public AuditViewDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AuditViewDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public AuditViewDto(Department source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Name.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// FoundationDate.
        /// </summary>
        [PropertyName("FoundationDate")]
        [CaptionProperty("")]
        public DateTime FoundationDate { get; set; } = DateTime.Now;

        /// <summary>
        /// Faculty.
        /// </summary>
        [PropertyName("Faculty")]
        [CaptionProperty("")]
        public Guid FacultyId { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override AuditViewDto FillFromClass(Department source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Name = source.Name;
            FoundationDate = source.FoundationDate.ToUniversalTime();
            FacultyId = PKHelper.GetGuidByObject(source.Faculty).GetValueOrDefault();

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Department destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Name = Name;
            destination.FoundationDate = FoundationDate.ToUniversalTime();

            if (FacultyId != Guid.Empty)
            {
                Faculty faculty = new Faculty();
                faculty.SetExistObjectPrimaryKey(FacultyId);
                destination.Faculty = faculty;
            }
            else
            {
                destination.Faculty = null;
            }

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
