//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Department
{
    using System;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Department.DepartmentD.
    /// </summary>
    [DataView(typeof(Department), "DepartmentD")]
    public partial class DepartmentDDto : DepartmentDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="DepartmentDDto"/>.
        /// </summary>
        public DepartmentDDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="DepartmentDDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public DepartmentDDto(Department source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Название.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("Название")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Специализация.
        /// </summary>
        [PropertyName("Specialization")]
        [CaptionProperty("Специализация")]
        public tDirection Specialization { get; set; }

        /// <summary>
        /// Наличие дополнительного образования.
        /// </summary>
        [PropertyName("HasAdditionalEducation")]
        [CaptionProperty("Наличие дополнительного образования")]
        public bool HasAdditionalEducation { get; set; } = false;

        /// <summary>
        /// Дата основания.
        /// </summary>
        [PropertyName("FoundationDate")]
        [CaptionProperty("Дата основания")]
        public DateTime FoundationDate { get; set; } = DateTime.Now;

        /// <summary>
        /// Устав кафедры.
        /// </summary>
        [PropertyName("Document")]
        [CaptionProperty("Устав кафедры")]
        public WebFile Document { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override DepartmentDDto FillFromClass(Department source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Name = source.Name;
            Specialization = source.Specialization;
            HasAdditionalEducation = source.HasAdditionalEducation;
            FoundationDate = source.FoundationDate.ToUniversalTime();
            Document = source.Document;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Department destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Name = Name;
            destination.Specialization = Specialization;
            destination.HasAdditionalEducation = HasAdditionalEducation;
            destination.FoundationDate = FoundationDate.ToUniversalTime();
            destination.Document = Document;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
