//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Department
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Qwe;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации DepartmentL.
    /// </summary>
    public partial class DepartmentLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DepartmentLFilterDto"/> class.
        /// </summary>
        public DepartmentLFilterDto()
        {
            DtoType = typeof(DepartmentLDto);
        }

        /// <summary>
        /// Название.
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// Название.
        /// </summary>
        public FilterOperation? NameOp { get; set; }
        /// <summary>
        /// Дата основания.
        /// </summary>
        public DateTime? FoundationDate { get; set; }

        /// <summary>
        /// Дата основания.
        /// </summary>
        public FilterOperation? FoundationDateOp { get; set; }
        /// <summary>
        /// Наличие дополнительного образования.
        /// </summary>
        public bool? HasAdditionalEducation { get; set; }

        /// <summary>
        /// Наличие дополнительного образования.
        /// </summary>
        public FilterOperation? HasAdditionalEducationOp { get; set; }
        /// <summary>
        /// Специализация.
        /// </summary>
        public tDirection? Specialization { get; set; }

        /// <summary>
        /// Специализация.
        /// </summary>
        public FilterOperation? SpecializationOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (NameOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Department>(NameOp.Value, d => d.Name, Name));
            }

            if (FoundationDateOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Department>(FoundationDateOp.Value, d => d.FoundationDate, FoundationDate));
            }

            if (HasAdditionalEducationOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Department>(HasAdditionalEducationOp.Value, d => d.HasAdditionalEducation, HasAdditionalEducation));
            }

            if (SpecializationOp != null)
            {
                limitFunctions.Add(GetFilterFunction<Department>(SpecializationOp.Value, d => d.Specialization, Specialization));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
