//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Qwe.ApplicationLayer.DTO.Department
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ICSSoft.STORMNET;
    using Qwe;
    using Qwe.ApplicationLayer;
    using Qwe.ApplicationLayer.Attributes;
    using Qwe.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления Department.DepartmentE.
    /// </summary>
    [DataView(typeof(Department), "DepartmentE")]
    public partial class DepartmentEDto : DepartmentDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="DepartmentEDto"/>.
        /// </summary>
        public DepartmentEDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="DepartmentEDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public DepartmentEDto(Department source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Название.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("Название")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Дата основания.
        /// </summary>
        [PropertyName("FoundationDate")]
        [CaptionProperty("Дата основания")]
        public DateTime FoundationDate { get; set; } = DateTime.Now;

        /// <summary>
        /// Наличие дополнительного образования.
        /// </summary>
        [PropertyName("HasAdditionalEducation")]
        [CaptionProperty("Наличие дополнительного образования")]
        public bool HasAdditionalEducation { get; set; } = false;

        /// <summary>
        /// Специализация.
        /// </summary>
        [PropertyName("Specialization")]
        [CaptionProperty("Специализация")]
        public tDirection Specialization { get; set; }

        /// <summary>
        /// Устав кафедры.
        /// </summary>
        [PropertyName("Document")]
        [CaptionProperty("Устав кафедры")]
        public WebFile Document { get; set; }

        /// <summary>
        /// Факультет.
        /// </summary>
        [PropertyName("Faculty")]
        [CaptionProperty("Факультет")]
        public Guid FacultyId { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Группа.
        /// </summary>
        public List<DTO.Group.GroupDDto> Group { get; set; } = new List<DTO.Group.GroupDDto>();

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override DepartmentEDto FillFromClass(Department source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Name = source.Name;
            FoundationDate = source.FoundationDate.ToUniversalTime();
            HasAdditionalEducation = source.HasAdditionalEducation;
            Specialization = source.Specialization;
            Document = source.Document;
            FacultyId = PKHelper.GetGuidByObject(source.Faculty).GetValueOrDefault();
            Group = source.Group.GetAllObjects().Cast<Group>().Select(d => new DTO.Group.GroupDDto(d)).ToList();

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(Department destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Name = Name;
            destination.FoundationDate = FoundationDate.ToUniversalTime();
            destination.HasAdditionalEducation = HasAdditionalEducation;
            destination.Specialization = Specialization;
            destination.Document = Document;

            if (FacultyId != Guid.Empty)
            {
                Faculty faculty = new Faculty();
                faculty.SetExistObjectPrimaryKey(FacultyId);
                destination.Faculty = faculty;
            }
            else
            {
                destination.Faculty = null;
            }

            DataObject[] detailsGroup = destination.Group.GetAllObjects();
            foreach (DTO.Group.GroupDDto detailDto in Group)
            {
                DataObject? detail = detailsGroup.FirstOrDefault(l => PKHelper.EQPK(l, detailDto.Id));
                if (detail == null)
                {
                    detail = new Group() { Department = destination };
                    destination.Group.AddObject(detail);
                }

                detailDto.UpdateFromDto((Group)detail);
            }

            foreach (Group detail in detailsGroup)
            {
                if (!Group.Any(a => PKHelper.EQPK(detail, a.Id)))
                {
                    detail.SetStatus(ObjectStatus.Deleted);
                }
            }

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
